#!/usr/bin/env python3
"""Phase A2, Parts 1 and 2: recover the historical comparison's numbers and test its data path.

Runs under `nd-unfolding/mnv_guarded_run.py` with `--expect-root` = the clean checkout of THIS
branch and `--allow` = the clean checkout of the comparison's code commit `68cf9d29`, from which
every scoring, split, tilt and loader function is imported (never re-implemented, except where a
deliberately independent cross-check is labelled as such).

Part 1 (scope section 3)
    * sha256 of every input, checked against the pins the comparison itself recorded;
    * leaf-by-leaf comparison of a report re-generated by the committed `report_campaign.py`
      (a separate guarded step of the same job) against the committed `campaign_report.json`;
    * an INDEPENDENT minimal re-implementation of the seven-bin recovery (np.histogram + L1),
      as a cross-check on the committed scorer rather than a replacement for it;
    * the aggregate and regional references and floors, recomputed from the inventory with the
      committed `reference_calibration.ceiling`, in BOTH candidate domains so it is explicit which
      one the frozen number is;
    * the directional diagnostic the report lacks: per-bin signed residual against the injected
      displacement, per run and per arm, aggregate and per region;
    * what per-iteration outputs exist.

Part 2 (scope section 5, A5)
    identity binding and uniqueness, the MC subsample, the stage split and the halves (by event
    identity, not by row), selection flags, dual-leg weights, the pseudodata tilt and the
    normalisation actually applied, masks and padding, and feature units AT THE MODEL INPUT
    (the executed loader, not a reading of it), plus the theirs-arm join and cache.

Writes receipts under --outdir. Never writes to the historical campaign directory. Reads real-data
members of the inventory NOT AT ALL, except that the committed loader itself touches them while
building the MC side; no statistic of them is recorded here.
"""
from __future__ import annotations

import argparse
import gc
import hashlib
import json
import math
import sys
import time
from pathlib import Path
from typing import Any

import numpy as np

TOL = 1e-10
STAGES = ("tuning", "pilot", "final")


# --------------------------------------------------------------------------- #
# small helpers
# --------------------------------------------------------------------------- #
def sha256(path: Path | str, chunk: int = 1 << 24) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as handle:
        while block := handle.read(chunk):
            h.update(block)
    return h.hexdigest()


def arr_sha(a: np.ndarray) -> str:
    return hashlib.sha256(np.ascontiguousarray(a).tobytes()).hexdigest()


def jsonable(o: Any) -> Any:
    if isinstance(o, dict):
        return {str(k): jsonable(v) for k, v in o.items()}
    if isinstance(o, (list, tuple)):
        return [jsonable(v) for v in o]
    if isinstance(o, np.ndarray):
        return jsonable(o.tolist())
    if isinstance(o, (np.floating,)):
        return float(o)
    if isinstance(o, (np.integer,)):
        return int(o)
    if isinstance(o, (np.bool_,)):
        return bool(o)
    if isinstance(o, float) and not math.isfinite(o):
        return repr(o)
    return o


def write(outdir: Path, name: str, payload: dict[str, Any]) -> None:
    path = outdir / name
    path.write_text(json.dumps(jsonable(payload), indent=1, sort_keys=False) + "\n")
    print(f"[a2] wrote {path}", flush=True)


def verdict(result: str, claim: str, evidence: dict[str, Any]) -> dict[str, Any]:
    assert result in ("PASS", "FAIL", "NOT-TESTABLE", "OBSERVATION")
    return {"result": result, "claim": claim, "evidence": evidence}


def flatten(obj: Any, prefix: str = "") -> dict[str, Any]:
    flat: dict[str, Any] = {}
    if isinstance(obj, dict):
        for k, v in obj.items():
            flat.update(flatten(v, f"{prefix}/{k}" if prefix else str(k)))
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            flat.update(flatten(v, f"{prefix}[{i}]"))
    else:
        flat[prefix] = obj
    return flat


def classify(a: Any, b: Any) -> str:
    if isinstance(a, bool) or isinstance(b, bool) or a is None or b is None:
        return "bit_identical" if a == b else "mismatch"
    if isinstance(a, (int, float)) and isinstance(b, (int, float)):
        if a == b:
            return "bit_identical"
        return ("within_1e-10" if abs(float(a) - float(b)) <= TOL * max(1.0, abs(float(a)))
                else "mismatch")
    return "bit_identical" if a == b else "mismatch"


# --------------------------------------------------------------------------- #
# Part 1a: the regenerated report against the committed one
# --------------------------------------------------------------------------- #
HEADLINE_LEAVES = (
    "absolute_adequacy/arms/ours/mean_recovery",
    "absolute_adequacy/arms/theirs/mean_recovery",
    "absolute_adequacy/reference", "absolute_adequacy/floor",
    "mean_recovery_by_region/ours/low_acceptance", "mean_recovery_by_region/ours/moderate",
    "mean_recovery_by_region/ours/good",
    "mean_recovery_by_region/theirs/low_acceptance", "mean_recovery_by_region/theirs/moderate",
    "mean_recovery_by_region/theirs/good",
    "interval/mean", "interval/sd", "interval/t_quantile", "interval/ci_low", "interval/ci_high",
    "regional_safeguard/floor/low_acceptance", "regional_safeguard/floor/moderate",
    "regional_safeguard/floor/good",
    "provenance/regional_reference/low_acceptance", "provenance/regional_reference/poor",
    "provenance/regional_reference/moderate", "provenance/regional_reference/good",
    "provenance/half_a_rows", "provenance/half_b_rows",
    "provenance/half_b_rows_dropped_not_truth_passing",
    "region_census/regions[0]/truth_mass_fraction",
    "verdict", "recommendation",
)


def compare_reports(committed: dict, recomputed: dict) -> dict[str, Any]:
    fa, fb = flatten(committed), flatten(recomputed)
    keys = sorted(set(fa) | set(fb))
    counts = {"bit_identical": 0, "within_1e-10": 0, "mismatch": 0, "missing": 0}
    mismatches = []
    for k in keys:
        if k not in fa or k not in fb:
            counts["missing"] += 1
            mismatches.append({"leaf": k, "committed": fa.get(k, "<absent>"),
                               "recomputed": fb.get(k, "<absent>")})
            continue
        c = classify(fa[k], fb[k])
        counts[c] += 1
        if c == "mismatch":
            mismatches.append({"leaf": k, "committed": fa[k], "recomputed": fb[k]})
    headline = {}
    for leaf in HEADLINE_LEAVES:
        headline[leaf] = {"committed": fa.get(leaf), "recomputed": fb.get(leaf),
                          "class": classify(fa.get(leaf), fb.get(leaf))}
    pairs = {k.split("/")[-1]: {"committed": fa[k], "recomputed": fb.get(k),
                                "class": classify(fa[k], fb.get(k))}
             for k in fa if k.startswith("paired_differences/")}
    return {"leaves": len(keys), "counts": counts, "mismatches": mismatches[:200],
            "headline": headline, "paired_differences": pairs}


# --------------------------------------------------------------------------- #
# Part 1b: an independent minimal scorer, as a cross-check
# --------------------------------------------------------------------------- #
def independent_recovery(eav_a, w_a, tilt_a, eav_b, w_b, push, edges):
    """The seven-bin score written from the specification, not imported.

    prior = w_truth over half-B truth-passing rows; unfolded = w_truth * push on the same rows;
    target = w_truth * tilt over half-A truth-passing rows; each normalised; R = 1 - |t-u|/|t-p|.
    """
    edges = np.asarray(edges, float)
    p, _ = np.histogram(eav_b, bins=edges, weights=w_b)
    u, _ = np.histogram(eav_b, bins=edges, weights=w_b * push)
    t, _ = np.histogram(eav_a, bins=edges, weights=w_a * tilt_a)
    p, u, t = p / p.sum(), u / u.sum(), t / t.sum()
    return float(1.0 - np.abs(t - u).sum() / np.abs(t - p).sum()), p, u, t


# --------------------------------------------------------------------------- #
# main
# --------------------------------------------------------------------------- #
def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--comparison-root", type=Path, required=True,
                    help="clean checkout of the comparison code commit (68cf9d29)")
    ap.add_argument("--campaign", type=Path, required=True)
    ap.add_argument("--closure-npz", type=Path, required=True)
    ap.add_argument("--identity-sidecar", type=Path, required=True)
    ap.add_argument("--inventory-receipt", type=Path, required=True)
    ap.add_argument("--committed-report", type=Path, required=True)
    ap.add_argument("--recomputed-report", type=Path, required=True)
    ap.add_argument("--theirs-index", type=Path, required=True)
    ap.add_argument("--production-root", type=Path, default=None,
                    help="the hardcoded production checkout the modules put on sys.path")
    ap.add_argument("--outdir", type=Path, required=True)
    ap.add_argument("--join-sample", type=int, default=4000)
    args = ap.parse_args(argv)
    args.outdir.mkdir(parents=True, exist_ok=True)
    t0 = time.time()

    root = args.comparison_root.resolve()
    cc = root / "nd-unfolding" / "pet" / "configuration_comparison"
    pet = root / "nd-unfolding" / "pet"
    for p in (str(root / "omnifold_nn"), str(pet), str(cc)):
        if p not in sys.path:
            sys.path.insert(0, p)
    # NumPy's optional SVE probe runs `lscpu` at `numpy.testing` import time, which TensorFlow
    # reaches through scipy; the OI-136 launch guard refuses any child it cannot prove keeps its
    # own Python launches guarded, and that refusal killed the first attempt at this job
    # (58742132). Measured caller:
    #   numpy/testing/_private/utils.py:1247 check_support_sve -> subprocess.run('lscpu').
    # NumPy's own fallback for that call is FileNotFoundError -> "no SVE", which is the right
    # answer on x86_64, so raise it rather than widen the guard. Same remedy, same reason, as
    # `nd-unfolding/pet/direct_token_comparison/calibration_measure.py:57`.
    import platform
    import shutil
    import subprocess
    if platform.machine() != "x86_64" and shutil.which("lscpu") is not None:
        raise SystemExit("[a2] the optional SVE probe cannot be answered offline on "
                         f"{platform.machine()}; refusing rather than launching lscpu")
    _real_run = subprocess.run

    def _run_without_sve_probe(command: Any, *rest: Any, **kw: Any) -> Any:
        if command == "lscpu" or (isinstance(command, (list, tuple)) and list(command)[:1]
                                  == ["lscpu"]):
            raise FileNotFoundError("optional SVE probe disabled: this is x86_64")
        return _real_run(command, *rest, **kw)

    subprocess.run = _run_without_sve_probe
    try:
        import numpy.testing  # noqa: F401
    finally:
        subprocess.run = _real_run

    # The engine package FIRST, from the pinned tree: `fullevent_fps_dataloader` puts the hardcoded
    # production root at sys.path[0] on import, and its late `from omnifold.dataloader import
    # DataLoader` would otherwise resolve there (the guard refuses that, correctly). Importing
    # `omnifold` pulls TensorFlow through `omnifold/__init__.py`, so this runs under the TF module.
    import omnifold  # noqa: F401
    import omnifold.dataloader  # noqa: F401
    import fullevent_fps_dataloader as ffd
    import theirs_loader_substitution  # noqa: F401
    import frozen_design as fd
    import score_campaign as sc
    import characterize_regions as cr
    import reference_calibration as rc
    import stage_splits as ss
    import closure_powered_truth_reweight as cp
    import run_arm_evaluation as rae
    import theirs_token_schema as tts
    import materialize_theirs as mtz

    committed = json.loads(args.committed_report.read_text())
    recomputed = json.loads(args.recomputed_report.read_text())

    # ================================================================== inputs
    runs: dict[str, list[dict[str, Any]]] = {}
    for stage in STAGES:
        runs[stage] = []
        for w in sorted((args.campaign / stage).rglob("weights_*.npz")):
            receipt = sc.receipt_path_for(w)
            runs[stage].append({"weights": str(w), "weights_sha256": sha256(w),
                                "receipt": str(receipt), "receipt_sha256": sha256(receipt)})
    pins = fd.PINNED_HASHES
    inputs = {
        "closure_npz": {"path": str(args.closure_npz), "sha256": sha256(args.closure_npz),
                        "expected_by_report": committed["provenance"]["closure_npz"]["sha256"]},
        "identity_sidecar": {"path": str(args.identity_sidecar),
                             "sha256": sha256(args.identity_sidecar),
                             "expected_by_frozen_design": pins["identity_sidecar"]},
        "inventory_receipt": {"path": str(args.inventory_receipt),
                              "sha256": sha256(args.inventory_receipt),
                              "expected_by_frozen_design":
                                  pins["inventory_receipt_G2_FPS_MEFHC_P12"]},
        "committed_report": {"path": str(args.committed_report),
                             "sha256": sha256(args.committed_report)},
        "recomputed_report": {"path": str(args.recomputed_report),
                              "sha256": sha256(args.recomputed_report)},
        "theirs_join_sig_npz": {"path": str(args.theirs_index / "join_sig.npz"),
                                "sha256": sha256(args.theirs_index / "join_sig.npz")},
        "theirs_join_sig_json": {"path": str(args.theirs_index / "join_sig.json"),
                                 "sha256": sha256(args.theirs_index / "join_sig.json")},
        "theirs_cache_final": {"path": str(args.campaign / "cache" / "theirs-final.npz"),
                               "sha256": sha256(args.campaign / "cache" / "theirs-final.npz")},
        "runs": runs,
    }
    for key in ("closure_npz", "identity_sidecar", "inventory_receipt"):
        ent = inputs[key]
        exp = ent.get("expected_by_report") or ent.get("expected_by_frozen_design")
        ent["matches_pin"] = ent["sha256"] == exp
    imported = {}
    for m in (fd, sc, cr, rc, ss, cp, rae, tts, mtz, ffd, omnifold, omnifold.dataloader):
        imported[m.__name__] = {"file": m.__file__, "sha256": sha256(m.__file__)}
    print(f"[a2] inputs hashed in {time.time() - t0:.0f}s", flush=True)

    # ================================================================== Part 1a
    report_diff = compare_reports(committed, recomputed)

    # ================================================================== load inventory
    with np.load(args.closure_npz, allow_pickle=False) as h:
        truth_scalars = np.asarray(h["truth_scalars"], dtype=np.float64)
        reco_scalars = np.asarray(h["reco_scalars"], dtype=np.float32)
        pass_truth = np.asarray(h["pass_truth"], dtype=bool)
        pass_reco = np.asarray(h["pass_reco"], dtype=bool)
        w_truth32 = np.asarray(h["w_truth"])
        w_reco32 = np.asarray(h["w_reco"])
        edges_pt = np.asarray(h["edges_0"], dtype=np.float64)
        edges_pz = np.asarray(h["edges_1"], dtype=np.float64)
        stored_sig_hash = str(np.asarray(h["sig_identity_hash"]).item())
        num_part = int(np.asarray(h["num_part"]).item())
        schema = str(np.asarray(h["petSchemaVersion"]).item())
    w_truth = w_truth32.astype(np.float64)
    w_reco = w_reco32.astype(np.float64)
    pt, pz, eavail = truth_scalars[:, 0], truth_scalars[:, 1], truth_scalars[:, 2]
    N = int(pass_truth.size)
    print(f"[a2] inventory loaded: {N} rows ({time.time() - t0:.0f}s)", flush=True)

    # ================================================================== Part 1c: references
    keep = pass_truth & np.isfinite(eavail)
    both = keep & pass_reco
    denom, _, _ = np.histogram2d(pt[keep], pz[keep], bins=[edges_pt, edges_pz],
                                 weights=w_truth[keep])
    numer, _, _ = np.histogram2d(pt[both], pz[both], bins=[edges_pt, edges_pz],
                                 weights=w_truth[both])
    with np.errstate(divide="ignore", invalid="ignore"):
        acc_cells = np.where(denom > 0, numer / denom, 0.0).ravel()
    tilt_all, spec_all = cp.clipped_exponential_tilt(
        eavail[keep], amplitude=float(fd.ENDPOINT["amplitude"]), clip_z=float(fd.ENDPOINT["clip"]))
    target_cells, _, _ = np.histogram2d(pt[keep], pz[keep], bins=[edges_pt, edges_pz],
                                        weights=w_truth[keep] * tilt_all)
    prior_f = (denom / denom.sum()).ravel()
    disp_cells = np.abs((target_cells / target_cells.sum()).ravel() - prior_f)
    ea_edges = np.asarray(fd.ENDPOINT["bin_edges_gev"], float)
    ea_den, _ = np.histogram(eavail[keep], bins=ea_edges, weights=w_truth[keep])
    ea_num, _ = np.histogram(eavail[both], bins=ea_edges, weights=w_truth[both])
    ea_acc = ea_num / ea_den
    ea_tgt, _ = np.histogram(eavail[keep], bins=ea_edges, weights=w_truth[keep] * tilt_all)
    ea_disp = np.abs(ea_tgt / ea_tgt.sum() - ea_den / ea_den.sum())
    ref_cells = {k: rc.ceiling(acc_cells, disp_cells, k) for k in (1, 2, 3, 4)}
    ref_bins = {k: rc.ceiling(ea_acc, ea_disp, k) for k in (1, 2, 3, 4)}
    regional = cr.regional_reference(acc_cells, disp_cells, 3)
    census = cr.region_census(acc_cells, prior_f, disp_cells)
    frozen_agg = float(fd.REFERENCE["aggregate"])
    reference = {
        "construction": ("reference_calibration.ceiling(acceptance, |target-prior|, k) over the "
                         "WHOLE truth-passing inventory, tilt from clipped_exponential_tilt on "
                         "the same rows; imported from the 68cf9d29 checkout"),
        "tilt_spec_whole_population": spec_all,
        "domain_pt_ppar_285_cells": {
            "reference_by_k": ref_cells,
            "k3_minus_frozen": ref_cells[3] - frozen_agg,
            "k3_class_vs_frozen": classify(frozen_agg, ref_cells[3]),
            "k3_minus_report": ref_cells[3] - committed["absolute_adequacy"]["reference"],
        },
        "domain_eavail_7_bins": {
            "acceptance": ea_acc, "displacement": ea_disp,
            "reference_by_k": ref_bins,
            "k3_minus_frozen": ref_bins[3] - frozen_agg,
        },
        "frozen_design_reference": {
            "aggregate": frozen_agg, "by_iterations": fd.REFERENCE["by_iterations"],
            "regional": fd.REFERENCE["regional"]},
        "which_domain_is_the_frozen_number": (
            "pt_ppar_285_cells" if abs(ref_cells[3] - frozen_agg) < 1e-12 else
            "eavail_7_bins" if abs(ref_bins[3] - frozen_agg) < 1e-12 else "neither"),
        "floor_recomputed": 0.8 * ref_cells[3],
        "floor_committed": committed["absolute_adequacy"]["floor"],
        "floor_class": classify(committed["absolute_adequacy"]["floor"], 0.8 * ref_cells[3]),
        "regional_reference_recomputed": regional,
        "regional_floor_recomputed": {k: 0.6 * v for k, v in regional.items()},
        "regional_floor_committed": committed["regional_safeguard"]["floor"],
        "regional_floor_class": {
            k: classify(committed["regional_safeguard"]["floor"][k], 0.6 * regional[k])
            for k in committed["regional_safeguard"]["floor"]},
        "census_recomputed": census,
        "low_acceptance_truth_mass_fraction": next(
            r["truth_mass_fraction"] for r in census["regions"] if r["region"] == "low_acceptance"),
    }
    print(f"[a2] references done ({time.time() - t0:.0f}s)", flush=True)

    # ================================================================== Part 1b/1d: per run
    per_run: dict[str, list[dict[str, Any]]] = {}
    endpoints = {}
    for stage in ("final", "pilot"):
        per_run[stage] = []
        first = Path(runs[stage][0]["weights"])
        import report_campaign as rcamp
        endpoint, context = rcamp.build_endpoint(args.closure_npz, first)
        endpoints[stage] = context
        scoreable = list(context["scoreable_regions"])
        for ent in runs[stage]:
            run = sc.load_run(ent["weights"])
            with np.load(ent["weights"]) as blob:
                rows_a = np.asarray(blob["dump_rows_a"]).astype(np.int64)
                rows_b = np.asarray(blob["dump_rows_b"]).astype(np.int64)
                tilt_a = np.asarray(blob["tilt_a"]).astype(np.float64)
                push = np.asarray(blob["weights"]).astype(np.float64)
                pg_b = np.asarray(blob["pass_gen_b"]).astype(bool)
            ka = pass_truth[rows_a] & np.isfinite(eavail[rows_a])
            kb = pass_truth[rows_b] & np.isfinite(eavail[rows_b])
            ind, p, u, t = independent_recovery(
                eavail[rows_a][ka], w_truth[rows_a][ka], tilt_a[ka],
                eavail[rows_b][kb], w_truth[rows_b][kb], push[kb], ea_edges)
            scored = sc.score_run(run, endpoint, scoreable_regions=scoreable)
            inj = t - p
            ach = u - p
            res = u - t
            with np.errstate(divide="ignore", invalid="ignore"):
                frac = np.where(inj != 0, ach / inj, np.nan)
            region_bins = {}
            for name in scoreable:
                la = np.asarray(endpoint.region_a) == name
                lb = np.asarray(endpoint.region_b) == name
                _r, pr_, ur_, tr_ = independent_recovery(
                    endpoint.eavail_a[la], endpoint.w_truth_a[la], endpoint.tilt_a[la],
                    endpoint.eavail_b[lb], endpoint.w_truth_b[lb],
                    push[kb][lb], ea_edges)
                ir, ar = tr_ - pr_, ur_ - pr_
                with np.errstate(divide="ignore", invalid="ignore"):
                    fr = np.where(ir != 0, ar / ir, np.nan)
                region_bins[name] = {"recovery_independent": _r,
                                     "recovery_committed_scorer": scored["recovery_by_region"][name],
                                     "prior": pr_, "target": tr_, "unfolded": ur_,
                                     "injected": ir, "signed_residual": ur_ - tr_,
                                     "achieved_fraction": fr}
            per_run[stage].append({
                "arm": run.arm, "seed": run.seed, "weights": ent["weights"],
                "recovery_committed_scorer": scored["recovery"],
                "recovery_independent": ind,
                "independent_minus_committed": ind - scored["recovery"],
                "class_independent_vs_committed": classify(scored["recovery"], ind),
                "overshoot_projection": scored["overshoot_projection"],
                "bins": {"edges_gev": ea_edges, "prior": p, "target": t, "unfolded": u,
                         "injected": inj, "achieved": ach, "signed_residual": res,
                         "achieved_fraction": frac},
                "bins_undershoot": int(np.sum((frac >= 0) & (frac < 1))),
                "bins_overshoot": int(np.sum(frac > 1)),
                "bins_wrong_direction": int(np.sum(frac < 0)),
                "regions": region_bins,
                "push_on_not_pass_gen_rows": {
                    "rows": int((~pg_b).sum()),
                    "all_exactly_one": bool(np.all(push[~pg_b] == 1.0)) if (~pg_b).any() else None},
                "push_stats_truth_passing": {
                    "min": float(push[kb].min()), "max": float(push[kb].max()),
                    "w_mean": float(np.average(push[kb], weights=w_truth[rows_b][kb])),
                    "ess_fraction": float(push[kb].sum() ** 2 / (push[kb] ** 2).sum() / kb.sum())},
            })
        print(f"[a2] {stage} runs scored ({time.time() - t0:.0f}s)", flush=True)

    def arm_summary(stage: str) -> dict[str, Any]:
        out = {}
        for arm in ("ours", "theirs"):
            rs = [r for r in per_run[stage] if r["arm"] == arm]
            fr = np.array([r["bins"]["achieved_fraction"] for r in rs], float)
            res = np.array([r["bins"]["signed_residual"] for r in rs], float)
            out[arm] = {
                "n": len(rs),
                "mean_recovery_committed_scorer": float(np.mean([r["recovery_committed_scorer"]
                                                                 for r in rs])),
                "mean_recovery_independent": float(np.mean([r["recovery_independent"] for r in rs])),
                "achieved_fraction_by_bin_mean": fr.mean(0), "achieved_fraction_by_bin_sd":
                    fr.std(0, ddof=1) if len(rs) > 1 else None,
                "signed_residual_by_bin_mean": res.mean(0),
                "injected_by_bin": rs[0]["bins"]["injected"],
                "runs_with_any_overshoot_bin": int(sum(r["bins_overshoot"] > 0 for r in rs)),
                "runs_with_any_wrong_direction_bin": int(sum(r["bins_wrong_direction"] > 0
                                                             for r in rs)),
                "regions": {
                    name: {"achieved_fraction_by_bin_mean":
                           np.nanmean(np.array([r["regions"][name]["achieved_fraction"]
                                                for r in rs], float), 0),
                           "signed_residual_by_bin_mean":
                           np.mean(np.array([r["regions"][name]["signed_residual"]
                                             for r in rs], float), 0),
                           "injected_by_bin": rs[0]["regions"][name]["injected"]}
                    for name in rs[0]["regions"]},
            }
        return out

    # the t interval, with an independent quantile
    try:
        from scipy import stats
        tq = float(stats.t.ppf(0.975, 7))
    except Exception as exc:  # pragma: no cover
        tq = f"scipy unavailable: {exc}"
    diffs = {}
    by = {(r["arm"], r["seed"]): r["recovery_independent"] for r in per_run["final"]}
    for seed in fd.SEEDS["final"]:
        diffs[seed] = by[("ours", seed)] - by[("theirs", seed)]
    d = np.array(list(diffs.values()))
    independent_interval = {
        "mean": float(d.mean()), "sd": float(d.std(ddof=1)), "t_quantile_scipy": tq,
        "ci_low": float(d.mean() - tq * d.std(ddof=1) / math.sqrt(d.size)) if isinstance(tq, float)
        else None,
        "ci_high": float(d.mean() + tq * d.std(ddof=1) / math.sqrt(d.size)) if isinstance(tq, float)
        else None,
        "paired_differences": diffs,
    }

    # per-iteration outputs. The question the brief asks is whether per-iteration EVENT weights
    # exist; a `.pkl` beside each checkpoint could be either a history or a weight array, so the
    # pickles are OPENED rather than classified by suffix.
    import pickle
    iteration_outputs = {}
    pickle_contents: dict[str, Any] = {}
    for stage in ("final",):
        for ent in runs[stage]:
            wdir = Path(ent["weights"]).parent
            names = sorted(p.name for p in wdir.iterdir())
            iteration_outputs[str(wdir)] = {
                "files": names,
                "event_weight_arrays": [n for n in names if n.endswith(".npz")],
                "checkpoints": [n for n in names if n.endswith(".weights.h5")],
                "pickles": [n for n in names if n.endswith(".pkl")],
            }
            for n in iteration_outputs[str(wdir)]["pickles"]:
                with open(wdir / n, "rb") as handle:
                    obj = pickle.load(handle)
                pickle_contents[str(wdir / n)] = {
                    "type": type(obj).__name__,
                    "keys": sorted(obj) if isinstance(obj, dict) else None,
                    "value_lengths": ({k: (len(v) if hasattr(v, "__len__") else None)
                                       for k, v in obj.items()} if isinstance(obj, dict) else None),
                    "holds_an_array_of_prior_length": bool(
                        isinstance(obj, dict) and any(
                            hasattr(v, "__len__") and len(v) == endpoints["final"]["half_b_rows"]
                            for v in obj.values())),
                }
    any_iter_weights = (any(len(v["event_weight_arrays"]) > 1 for v in iteration_outputs.values())
                        or any(v["holds_an_array_of_prior_length"]
                               for v in pickle_contents.values()))
    # the engine's own normalisation lines, read from the executed tasks' logs
    norm_lines: dict[str, list[str]] = {}
    for ent in runs["final"]:
        log = Path(ent["weights"]).parent.parent / "run.log"
        if log.exists():
            norm_lines[str(log)] = [ln.strip() for ln in log.read_text(errors="replace").splitlines()
                                    if "Normalizing sum of weights" in ln]
    distinct_norm = sorted({tuple(v) for v in norm_lines.values()})

    part1 = {
        "scope": "Phase A2 Part 1: recover and recompute the historical headline (scope section 3)",
        "inputs": inputs, "imported_modules": imported,
        "regenerated_report_vs_committed": report_diff,
        "independent_scorer_cross_check": {
            "final": [{k: r[k] for k in ("arm", "seed", "recovery_committed_scorer",
                                          "recovery_independent", "independent_minus_committed",
                                          "class_independent_vs_committed")}
                      for r in per_run["final"]],
            "interval_from_independent_scores": independent_interval,
        },
        "reference": reference,
        "endpoint_context_final": {k: endpoints["final"][k] for k in
                                   ("half_a_rows", "half_b_rows",
                                    "half_b_rows_dropped_not_truth_passing", "halves_disjoint",
                                    "off_grid_truth_fraction", "regional_reference")},
        "per_iteration": {
            "per_iteration_event_weights_exist": any_iter_weights,
            "reading": ("each run directory holds ONE event-weight array (the final push) plus a "
                        "Keras checkpoint and a pickle per (iteration, step); the pickles were "
                        "OPENED and hold only per-epoch training history. Per-iteration recovery "
                        "is therefore NOT recoverable from saved event weights; the route that "
                        "exists is re-inference of each iteration's step-2 checkpoint on half B's "
                        "truth cloud (48 inferences over ~600 k rows), which is a GPU job outside "
                        "this task's CPU scope."),
            "listing_final": iteration_outputs,
            "pickle_contents": pickle_contents,
        },
        "engine_normalisation_lines_in_the_executed_logs": {
            "distinct_line_sequences": [list(t) for t in distinct_norm],
            "runs_with_a_log": len(norm_lines),
            "reading": ("what the engine printed while the historical tasks ran, not a reading of "
                        "the loader's source"),
        },
    }
    write(args.outdir, "recompute_scores.json", part1)
    directional = {
        "scope": ("Directional diagnostic the report lacks. Per bin: injected = target - prior, "
                  "achieved = unfolded - prior, signed_residual = unfolded - target, "
                  "achieved_fraction = achieved / injected (<0 wrong direction, 0..1 undershoot, "
                  ">1 overshoot). All spectra normalised, half-B prior/unfolded, half-A target."),
        "final_by_arm": arm_summary("final"),
        "pilot_by_arm": arm_summary("pilot"),
        "final_per_run": per_run["final"],
        "pilot_per_run": per_run["pilot"],
    }
    write(args.outdir, "recompute_directional.json", directional)
    del per_run
    gc.collect()

    # ================================================================== Part 2
    checks: dict[str, Any] = {}
    side = np.load(args.identity_sidecar, allow_pickle=False)
    ev_id = np.asarray(side["sig_event_id"]).astype(np.int64)            # (N,3)
    ev_src = np.asarray(side["sig_event_source"]).astype(np.int64)
    ev_occ = np.asarray(side["sig_event_occurrence"]).astype(np.int64)
    ev_key = np.asarray(side["sig_event_key"])
    side_bound = str(np.asarray(side["sig_bound_identity_hash"]).item())
    fields = [str(x) for x in np.asarray(side["sig_identity_fields"])]

    # A5.1 binding
    recomputed_hash = ffd.inventory_order_hash(w_truth32, pass_truth)
    checks["identity_binding"] = verdict(
        "PASS" if (recomputed_hash == stored_sig_hash == side_bound and ev_id.shape[0] == N)
        else "FAIL",
        "the identity sidecar is bound to this inventory, row for row",
        {"inventory_stored_sig_identity_hash": stored_sig_hash,
         "recomputed_inventory_order_hash(w_truth,pass_truth)": recomputed_hash,
         "sidecar_sig_bound_identity_hash": side_bound,
         "sidecar_rows": int(ev_id.shape[0]), "inventory_rows": N,
         "identity_fields": fields})

    # A5.2 uniqueness
    packed = (ev_id[:, 0] << 42) | (ev_id[:, 1] << 21) | ev_id[:, 2]
    assert ev_id.max() < (1 << 21) and ev_id.min() >= 0
    n_unique = int(np.unique(packed).size)
    n_unique_src = int(np.unique(np.stack([packed, ev_src], 1), axis=0).shape[0])
    key_unique = int(np.unique(ev_key).size)
    checks["identity_uniqueness"] = verdict(
        "PASS" if n_unique == N else "FAIL",
        "(mc_run, mc_subrun, mc_nthEvtInFile) identifies one inventory row; rows are events",
        {"rows": N, "distinct_(run,subrun,nth)": n_unique,
         "distinct_(run,subrun,nth,source)": n_unique_src,
         "distinct_sig_event_key": key_unique,
         "max_occurrence": int(ev_occ.max()), "min_occurrence": int(ev_occ.min()),
         "sources_present": np.unique(ev_src).tolist()})

    # A5.3 the subsample: re-derive imc and compare with every run's mc_indices
    rng_imc = np.sort(np.random.default_rng(0).choice(N, 2_000_000, replace=False))
    mc_idx = {}
    for stage in STAGES:
        for ent in runs[stage]:
            with np.load(ent["weights"]) as blob:
                mi = np.asarray(blob["mc_indices"]).astype(np.int64)
            mc_idx[ent["weights"]] = bool(np.array_equal(mi, rng_imc))
    checks["mc_subsample"] = verdict(
        "PASS" if all(mc_idx.values()) else "FAIL",
        ("every run's mc_indices equals sort(default_rng(0).choice(N, 2_000_000, "
         "replace=False)), the loader's subsample"),
        {"runs_checked": len(mc_idx), "all_equal": all(mc_idx.values()),
         "subsample_rows": int(rng_imc.size), "inventory_rows": N,
         "fraction_of_inventory": rng_imc.size / N, "imc_sha256": arr_sha(rng_imc)})

    # A5.4 stage split and halves, re-derived and tested by identity
    ident_sub = ev_id[rng_imc]
    labels = ss.assign(ident_sub)
    stage_rows = {s: rng_imc[labels == s] for s in STAGES}
    split = {"counts": {s: int(stage_rows[s].size) for s in STAGES}}
    halves = {}
    for stage in STAGES:
        shas = set()
        for ent in runs[stage]:
            with np.load(ent["weights"]) as blob:
                ra = np.asarray(blob["dump_rows_a"]).astype(np.int64)
                rb = np.asarray(blob["dump_rows_b"]).astype(np.int64)
            shas.add((arr_sha(ra), arr_sha(rb)))
        pos = np.flatnonzero(labels == stage)
        half = pos.size // 2
        ja, jb = cp.deterministic_halves(pos.size, half=half, seed=int(fd.SPLITS["split_seed"]))
        ea, eb = rng_imc[pos[ja]], rng_imc[pos[jb]]
        halves[stage] = {
            "rows_a": ra, "rows_b": rb, "rederived_equal_a": bool(np.array_equal(ea, ra)),
            "rederived_equal_b": bool(np.array_equal(eb, rb)),
            "distinct_half_pairs_across_runs": len(shas), "half_size": int(half),
            "stage_rows": int(pos.size),
            "stage_rows_left_out_of_both_halves": int(pos.size - 2 * half)}
    ident_sets = {}
    for stage in STAGES:
        for side_name in ("a", "b"):
            rows = halves[stage][f"rows_{side_name}"]
            ident_sets[f"{stage}_{side_name}"] = packed[rows]
    overlaps = {}
    names = list(ident_sets)
    for i, a in enumerate(names):
        for b in names[i + 1:]:
            overlaps[f"{a}&{b}"] = int(np.intersect1d(ident_sets[a], ident_sets[b]).size)
    inside = {s: bool(np.isin(np.concatenate([halves[s]["rows_a"], halves[s]["rows_b"]]),
                              stage_rows[s]).all()) for s in STAGES}
    ok = (all(v == 0 for v in overlaps.values()) and all(inside.values())
          and all(halves[s]["rederived_equal_a"] and halves[s]["rederived_equal_b"]
                  and halves[s]["distinct_half_pairs_across_runs"] == 1 for s in STAGES))
    checks["split_isolation"] = verdict(
        "PASS" if ok else "FAIL",
        ("tuning/pilot/final and halves A/B are pairwise disjoint BY EVENT IDENTITY; each "
         "stage's halves are re-derived bit-for-bit from the committed split code; every run in a "
         "stage used the same halves"),
        {"stage_split": split, "identity_overlap_counts": overlaps,
         "halves_inside_own_stage": inside,
         "halves": {s: {k: v for k, v in halves[s].items() if not k.startswith("rows_")}
                    for s in STAGES},
         "stage_assignment": "stage_splits.assign(sig_event_id) = blake2b hash of "
                             "(mc_run, mc_subrun, mc_nthEvtInFile) salted with split_seed 20260920",
         "halves_assignment": "closure_powered_truth_reweight.deterministic_halves(stage rows, "
                              "half=stage_rows//2, seed=20260920): one seeded permutation of the "
                              "stage's POSITIONS, sliced twice -- a row split; it is an event "
                              "split only because rows are unique events (identity_uniqueness)"})

    # A5.5 selection flags, whole inventory and final halves
    fa, fb = halves["final"]["rows_a"], halves["final"]["rows_b"]

    def flag_counts(rows: np.ndarray | None) -> dict[str, int]:
        pt_, pr_ = (pass_truth, pass_reco) if rows is None else (pass_truth[rows], pass_reco[rows])
        return {"rows": int(pt_.size), "pass_truth": int(pt_.sum()), "pass_reco": int(pr_.sum()),
                "both": int((pt_ & pr_).sum()), "miss_truth_only": int((pt_ & ~pr_).sum()),
                "fake_reco_only": int((~pt_ & pr_).sum()), "neither": int((~pt_ & ~pr_).sum())}
    fc = {"inventory": flag_counts(None), "final_half_a": flag_counts(fa),
          "final_half_b": flag_counts(fb), "subsample": flag_counts(rng_imc)}
    # the sentinel convention on !pass_reco rows
    npr = ~pass_reco
    sentinel_ok = bool(np.all(reco_scalars[npr] == -9999.0))
    checks["selection_flags"] = verdict(
        "PASS" if (fc["final_half_a"]["pass_truth"] == committed["provenance"]["half_a_rows"]
                   and fc["final_half_b"]["pass_truth"] == committed["provenance"]["half_b_rows"]
                   and fc["final_half_b"]["rows"] - fc["final_half_b"]["pass_truth"]
                   == committed["provenance"]["half_b_rows_dropped_not_truth_passing"]
                   and fc["inventory"]["neither"] == 0 and sentinel_ok) else "FAIL",
        ("flags partition the inventory into both / miss / fake with no 'neither' row; the "
         "report's half counts are the truth-passing rows of each half; !pass_reco rows carry the "
         "-9999 reco sentinel"),
        {"counts": fc, "reco_scalars_sentinel_on_every_not_pass_reco_row": sentinel_ok,
         "how_each_enters (from run_arm_evaluation.evaluate, 68cf9d29)": {
             "pseudodata_step1": "half A rows with pass_reco & pass_gen (fakes and misses excluded)",
             "prior_step1": "half B, pass_reco := pass_reco & pass_gen (fakes excluded)",
             "prior_step2": "half B, pass_gen (misses included, fakes excluded)",
             "score_target": "half A pass_truth rows, w_truth * tilt (misses included)",
             "score_prior_and_unfolded": "half B pass_truth rows, w_truth and w_truth * push",
             "fakes": "enter nothing: not step 1 (either leg), not step 2, not the score"}})

    # A5.6 dual-leg weights
    both_all = pass_truth & pass_reco
    ratio = w_reco[both_all] / w_truth[both_all]
    miss = pass_truth & ~pass_reco
    checks["dual_leg_weights"] = verdict(
        "PASS" if (np.all(np.isfinite(w_truth)) and np.all(np.isfinite(w_reco))
                   and np.all(w_truth > 0) and np.all(w_reco > 0)) else "FAIL",
        "w_truth and w_reco are finite, positive, row-aligned; their relation is measured",
        {"w_truth": {"min": w_truth.min(), "max": w_truth.max(), "mean": w_truth.mean()},
         "w_reco": {"min": w_reco.min(), "max": w_reco.max(), "mean": w_reco.mean()},
         "ratio_w_reco_over_w_truth_on_both": {
             "min": ratio.min(), "max": ratio.max(), "mean": ratio.mean(),
             "fraction_exactly_1": float(np.mean(ratio == 1.0)),
             "quantiles_1_50_99": np.quantile(ratio, [0.01, 0.5, 0.99])},
         "miss_rows_w_reco_equals_w_truth": float(np.mean(w_reco[miss] == w_truth[miss])),
         "fake_rows": int((~pass_truth & pass_reco).sum()),
         "where_each_enters": {
             "w_reco": "step 1, both legs (pseudodata w_reco*tilt; prior weight_reco)",
             "w_truth": "step 2 and every truth-space spectrum in the score",
             "source": "runEventLoopOmniFold.cpp: w_reco = model.GetWeight(reco universe), "
                       "w_truth = model.GetWeight(truth universe); misses carry w_reco := w_truth"}})

    # A5.7 pseudodata: tilt as executed, and the normalisation applied
    with np.load(runs["final"][0]["weights"]) as blob:
        tilt_a_saved = np.asarray(blob["tilt_a"]).astype(np.float64)
        pg_a_saved = np.asarray(blob["pass_gen_a"]).astype(bool)
    pg_a = pass_truth[fa]
    tilt_re, spec_re = cp.clipped_exponential_tilt(
        eavail[fa][pg_a], amplitude=float(fd.ENDPOINT["amplitude"]),
        clip_z=float(fd.ENDPOINT["clip"]))
    tilt_full = np.ones(fa.size)
    tilt_full[pg_a] = tilt_re
    z = (eavail[fa][pg_a] - spec_re["pt_p50"]) / spec_re["pt_iqr"]
    s1a = pass_reco[fa] & pg_a
    s1b = pass_reco[fb] & pass_truth[fb]
    wa_reco_tilt = (w_reco[fa] * tilt_full)[s1a]
    t_acc_w = float(wa_reco_tilt.sum() / w_reco[fa][s1a].sum())
    r_physical = float(wa_reco_tilt.sum() / w_reco[fb][s1b].sum())
    receipt0 = json.loads(Path(runs["final"][0]["receipt"]).read_text())
    run_spec = receipt0["closure"]["injection"]
    same_spec = all(abs(run_spec[k] - spec_re[k]) == 0 for k in
                    ("pt_p25", "pt_p50", "pt_p75", "pt_iqr", "pre_normalization_mean"))
    checks["pseudodata_tilt"] = verdict(
        "PASS" if (np.array_equal(tilt_full, tilt_a_saved) and np.array_equal(pg_a, pg_a_saved)
                   and same_spec) else "FAIL",
        ("the saved tilt is exp(0.35*clip((E_avail-p50)/IQR, -3, +3))/mean(...) over half A's "
         "truth-passing rows, re-derived bit-for-bit; 1 on non-truth rows"),
        {"formula": spec_re["form"] + "  [keys named pt_* are E_avail quantiles in GeV]",
         "standardisation_constants_gev": {k: spec_re[k] for k in
                                            ("pt_p25", "pt_p50", "pt_p75", "pt_iqr")},
         "pre_normalization_mean": spec_re["pre_normalization_mean"],
         "clip_z": spec_re["clip_z"], "amplitude": spec_re["amplitude"],
         "raw_eavail_at_upper_clip_gev": spec_re["pt_p50"] + 3.0 * spec_re["pt_iqr"],
         "raw_eavail_at_lower_clip_gev": spec_re["pt_p50"] - 3.0 * spec_re["pt_iqr"],
         "fraction_rows_clipped_high": float(np.mean(z > 3.0)),
         "fraction_rows_clipped_low": float(np.mean(z < -3.0)),
         "tilt_min": float(tilt_re.min()), "tilt_max": float(tilt_re.max()),
         "unweighted_mean_tilt_on_injected_rows": float(tilt_re.mean()),
         "w_truth_weighted_mean_tilt_on_injected_rows":
             float(np.average(tilt_re, weights=w_truth[fa][pg_a])),
         "bit_identical_to_saved_tilt_a": bool(np.array_equal(tilt_full, tilt_a_saved)),
         "receipt_spec_equals_rederived": same_spec,
         "census_tilt_constants_whole_population_differ": {
             k: spec_all[k] for k in ("pt_p25", "pt_p50", "pt_p75", "pt_iqr")},
         "census_tilt_used_for": ("region census and references only (report_campaign."
                                  "build_endpoint); the SCORE target uses the saved half-A tilt")})
    checks["pseudodata_normalisation"] = verdict(
        "OBSERVATION",
        ("both step-1 classes are normalised to 1e6: pdata sum(w_reco*tilt over s1_a) and prior "
         "sum(weight_reco over s1_b). The ratio the tilt would imply is discarded"),
        {"pdata_rows_s1_a": int(s1a.sum()), "receipt_pdata_rows": receipt0["closure"]["pdata_rows"],
         "prior_rows_half_b": int(fb.size), "prior_step1_rows_s1_b": int(s1b.sum()),
         "w_reco_weighted_mean_tilt_over_s1_a": t_acc_w,
         "physical_class_ratio_sum_s1a_wreco_tilt_over_sum_s1b_wreco": r_physical,
         "class_ratio_used": 1.0,
         "execution_evidence_lines_measured_in_the_run_logs": [list(t) for t in distinct_norm],
         "execution_evidence_runs_with_a_log": len(norm_lines),
         "consequence (INFERRED)": ("step 1 reweights accepted rows by r(x)/R_phys relative to "
                                    "misses, whose pull weight stays 1; a shape-only closure. "
                                    "Its effect on recovery is not measured here (Phase B)")})

    # A5.8 masks and padding in the inventory rows the final stage used
    used = np.union1d(fa, fb)
    with np.load(args.closure_npz, allow_pickle=False) as h:
        part_reco = np.asarray(h["part_reco"])[used]
        reco_view = np.asarray(h["reco_view"])[used]
        reco_time = np.asarray(h["reco_time"])[used]
        part_gen = np.asarray(h["part_gen"])[used]
    real_r = part_reco[:, :, 0] != 0
    real_g = part_gen[:, :, 0] != 0
    pr_u, pt_u = pass_reco[used], pass_truth[used]
    ntok_r, ntok_g = real_r.sum(1), real_g.sum(1)

    def tail_order_ok(real: np.ndarray) -> bool:
        # real tokens first, then pads: no real token after a pad
        return bool(np.all(np.diff(real.astype(np.int8), axis=1) <= 0))
    e_desc = bool(np.all(np.diff(np.where(real_r, part_reco[:, :, 0], -1e30), axis=1) <= 0))
    checks["masks_and_padding"] = verdict(
        "PASS" if (tail_order_ok(real_r) and tail_order_ok(real_g)
                   and np.all(part_reco[~real_r] == 0) and np.all(part_gen[~real_g] == 0)
                   and np.all(reco_view[~real_r] == 0) and np.all(reco_time[~real_r] == 0)
                   and np.all(ntok_r[~pr_u] == 0)) else "FAIL",
        ("pads are all-zero and trail the real tokens (mask = column 0 != 0, as PET reads it); "
         "!pass_reco rows carry no reco token"),
        {"rows_checked": int(used.size), "num_part_cap": num_part, "schema": schema,
         "reco_tokens_per_event_on_pass_reco": np.bincount(ntok_r[pr_u], minlength=num_part + 1),
         "reco_fraction_at_cap_on_pass_reco": float(np.mean(ntok_r[pr_u] == num_part)),
         "reco_pass_rows_with_zero_tokens": int((ntok_r[pr_u] == 0).sum()),
         "reco_tokens_on_not_pass_reco_rows": int(ntok_r[~pr_u].sum()),
         "reco_energy_descending_within_event": e_desc,
         "reco_tokens_with_negative_energy": int((part_reco[:, :, 0] < 0).sum()),
         "gen_tokens_per_event_on_pass_truth": np.bincount(ntok_g[pt_u], minlength=num_part + 1),
         "gen_fraction_at_cap_on_pass_truth": float(np.mean(ntok_g[pt_u] == num_part)),
         "gen_pass_truth_rows_with_zero_tokens": int((ntok_g[pt_u] == 0).sum()),
         "gen_pdg_values_top": dict(zip(*[x.tolist() for x in np.unique(
             part_gen[:, :, 4][real_g].astype(np.int64), return_counts=True)])),
         "view_values_on_real_tokens": dict(zip(*[x.tolist() for x in np.unique(
             reco_view[real_r].astype(np.int64), return_counts=True)])),
         "truncation": ("dump_pointcloud_inputs._pad_tokens keeps the top num_part tokens by "
                        "energy and DROPS the rest; no overflow summary is written")})
    del part_reco, part_gen, reco_view, reco_time
    gc.collect()

    # A5.9 the theirs join and cache
    join = json.loads((args.theirs_index / "join_sig.json").read_text())
    jidx = np.load(args.theirs_index / "join_sig.npz")
    row_index, origin = np.asarray(jidx["row_index"]), np.asarray(jidx["origin"])
    files = join["files"]
    cache = np.load(args.campaign / "cache" / "theirs-final.npz")
    rows_a_c, rows_b_c = np.asarray(cache["rows_a"]), np.asarray(cache["rows_b"])
    s1_a_c = np.asarray(cache["s1_a"]).astype(bool)
    rng = np.random.default_rng(20260922)
    # Sample inside a random subset of shards so the check opens tens of shards, not all 978.
    reco_b_pos = np.flatnonzero(pass_reco[fb])
    shard_of = origin[row_index[fb[reco_b_pos]], 0]
    shards = rng.choice(np.unique(shard_of), size=min(25, np.unique(shard_of).size),
                        replace=False)
    candidates = reco_b_pos[np.isin(shard_of, shards)]
    sample_pos = np.sort(rng.choice(candidates, size=min(args.join_sample, candidates.size),
                                    replace=False))
    sample_rows = fb[sample_pos]
    gathered = mtz.materialize(files, row_index, origin, sample_rows, pass_reco)
    prior_packed = np.asarray(cache["prior_packed"])[sample_pos]
    prior_glob = np.asarray(cache["prior_globals"])[sample_pos]
    # identity: the shard row each sampled inventory row resolves to must carry its identity
    sel = row_index[sample_rows]
    where = origin[sel]
    id_ok = 0
    for shard in np.unique(where[:, 0]):
        m = where[:, 0] == shard
        with np.load(files[shard]) as blob:
            shard_id = np.asarray(blob["identity"])[where[m, 1]].astype(np.int64)
        id_ok += int(np.all(shard_id == ev_id[sample_rows[m]], axis=1).sum())
    matched_reco = int(((row_index >= 0) & pass_reco).sum())
    checks["theirs_join_and_cache"] = verdict(
        "PASS" if (id_ok == sample_rows.size
                   and np.array_equal(gathered["packed"], prior_packed)
                   and np.array_equal(gathered["globals"], prior_glob)
                   and np.array_equal(rows_a_c, fa) and np.array_equal(rows_b_c, fb)
                   and np.array_equal(s1_a_c, s1a)
                   and join.get("duplicate_built_keys") == 0
                   and join.get("positional_fallback") == "never") else "FAIL",
        ("his tokens are joined by event identity: a random sample of half-B pass_reco rows "
         "resolves to shard rows carrying the SAME (run, subrun, nth); a fresh gather equals the "
         "cache the tasks read; the cache's rows equal the runs' halves"),
        {"join_report": {k: join[k] for k in ("stream", "identity_fields", "inventory_rows",
                                               "built_rows", "built_files", "matched",
                                               "unmatched", "match_fraction",
                                               "duplicate_built_keys", "positional_fallback",
                                               "reco_coverage") if k in join},
         "pass_reco_rows_with_a_built_input": matched_reco,
         "pass_reco_rows_total": int(pass_reco.sum()),
         "sample_rows": int(sample_rows.size), "sample_identity_equal": id_ok,
         "fresh_gather_equals_cache_packed": bool(np.array_equal(gathered["packed"],
                                                                 prior_packed)),
         "fresh_gather_equals_cache_globals": bool(np.array_equal(gathered["globals"],
                                                                  prior_glob)),
         "cache_rows_equal_run_halves": bool(np.array_equal(rows_a_c, fa)
                                             and np.array_equal(rows_b_c, fb)),
         "cache_s1_a_equals_pass_reco_and_pass_gen": bool(np.array_equal(s1_a_c, s1a)),
         "cache_key": str(np.asarray(cache["key"]))})

    # theirs model-input features (the cache is what the tasks read)
    pp = np.asarray(cache["prior_packed"])
    pgl = np.asarray(cache["prior_globals"])
    real_t = pp[:, :, 3] != 0
    pr_b = pass_reco[fb]
    tok_t = real_t.sum(1)
    col_names = ["eta", "phi", "log_pT", "log_E", "pid", "dedx_pre", "x/div", "y/div", "z/div",
                 "t/div"]
    theirs_cols = {}
    for j, name in enumerate(col_names):
        v = pp[:, :, j][real_t]
        theirs_cols[name] = {"min": float(v.min()), "p01": float(np.quantile(v, 0.01)),
                             "median": float(np.median(v)), "p99": float(np.quantile(v, 0.99)),
                             "max": float(v.max())}
    pids, pid_counts = np.unique(pp[:, :, 4][real_t].astype(np.int64), return_counts=True)
    glob_cols = {}
    for j in range(pgl.shape[1]):
        v = pgl[pr_b, j]
        glob_cols[j] = {"min": float(v.min()), "median": float(np.median(v)),
                        "max": float(v.max()), "fraction_zero": float(np.mean(v == 0))}
    checks["theirs_model_inputs"] = verdict(
        "PASS" if (np.all(pp[~pr_b] == 0) and np.all(pgl[~pr_b] == 0)) else "FAIL",
        "his step-1 inputs (as the tasks read them): !pass_reco rows all-zero; ranges measured",
        {"prior_rows": int(pp.shape[0]), "cap": int(pp.shape[1]),
         "tokens_per_event_pass_reco": np.bincount(tok_t[pr_b], minlength=pp.shape[1] + 1),
         "fraction_at_cap_pass_reco": float(np.mean(tok_t[pr_b] == pp.shape[1])),
         "fraction_with_aggregate_blob_pid6":
             float(np.mean((pp[:, :, 4] == 6).any(1)[pr_b])),
         "fraction_with_aggregate_prong_pid7":
             float(np.mean((pp[:, :, 4] == 7).any(1)[pr_b])),
         "pid_counts": dict(zip(pids.tolist(), pid_counts.tolist())),
         "token_columns_on_real_tokens": theirs_cols,
         "globals_on_pass_reco_rows": glob_cols,
         "mask": "log E != 0 (column 3), per theirs_token_schema.convert_packed"})
    del pp, pgl, cache
    gc.collect()
    print(f"[a2] identity/split/flags/weights/tilt/masks/join done ({time.time() - t0:.0f}s)",
          flush=True)

    # A5.10 feature units at the model input: run the executed loader itself
    del truth_scalars, reco_scalars, ev_key
    gc.collect()
    _data, mc, imc, coord_reco, coord_gen, meta = ffd.build_fullevent_loaders(
        str(args.closure_npz), max_events=2_000_000, seed=0, bkg_mode="mc-only")
    imc = np.asarray(imc)
    reco = np.asarray(mc.reco)
    gen = np.asarray(mc.gen)
    reco_evt = np.asarray(mc.reco_evt)
    gen_evt = np.asarray(mc.gen_evt)
    prl, pgl_ = np.asarray(mc.pass_reco).astype(bool), np.asarray(mc.pass_gen).astype(bool)

    def col_stats(x: np.ndarray, mask: np.ndarray) -> dict[str, Any]:
        v = x[mask]
        return {"min": float(v.min()), "p01": float(np.quantile(v, 0.01)),
                "median": float(np.median(v)), "p99": float(np.quantile(v, 0.99)),
                "max": float(v.max()), "mean": float(v.mean()), "std": float(v.std())}
    rr = reco[:, :, 0] != 0
    gg = gen[:, :, 0] != 0
    reco_cols = meta.get("reco_cloud_cols", ["E", "pos", "z", "view", "time"])
    gen_cols = ["E_GeV", "px_GeV", "py_GeV", "pz_GeV", "pdg", "theta", "cos_phi", "sin_phi"]
    units = {
        "reco_cloud": {"columns": reco_cols,
                       "units": ["GeV (MeV/1000)", "m (mm/1000)", "m (mm/1000)",
                                 "view code 1/2/3", "ns/100"],
                       "coord_idx": list(coord_reco),
                       "stats_on_real_tokens": {c: col_stats(reco[:, :, j], rr)
                                                for j, c in enumerate(reco_cols)}},
        "gen_cloud": {"columns": gen_cols, "coord_idx": list(coord_gen),
                      "stats_on_real_tokens": {c: col_stats(gen[:, :, j], gg)
                                               for j, c in enumerate(gen_cols)}},
        "reco_evt": {"names": meta.get("feature_names"),
                     "stats_on_pass_reco": {str(j): col_stats(reco_evt[:, j], prl)
                                            for j in range(reco_evt.shape[1])},
                     "zero_on_not_pass_reco": bool(np.all(reco_evt[~prl] == 0))},
        "gen_evt": {"names": meta.get("truth_feature_names"),
                    "stats_on_pass_gen": {str(j): col_stats(gen_evt[:, j], pgl_)
                                          for j in range(gen_evt.shape[1])}},
        "normalisation_meta": {k: meta[k] for k in meta if "norm" in k},
        "normalisation_statistic_rows": ("reco: pass_reco rows of the WHOLE 2M subsample (all "
                                         "three stages, both halves); truth: pass_truth rows of "
                                         "the same -- a shared preprocessing constant"),
        "meta_keys": sorted(meta.keys()),
        "weights": {"sum_weight_reco_on_pass_reco": float(np.asarray(mc.weight_reco)[prl].sum()),
                    "sum_weight_on_pass_reco": float(np.asarray(mc.weight)[prl].sum())},
    }
    loader_ok = (np.array_equal(imc, rng_imc)
                 and np.array_equal(prl, pass_reco[imc]) and np.array_equal(pgl_, pass_truth[imc]))
    checks["feature_units_at_model_input"] = verdict(
        "PASS" if loader_ok and units["reco_evt"]["zero_on_not_pass_reco"] else "FAIL",
        ("the executed loader (68cf9d29, bkg_mode='mc-only', max_events=2e6, seed 0) returns the "
         "same subsample and flags as the inventory; inputs are GeV/m/ns-scaled clouds and "
         "z-normalised event blocks; !pass_reco event rows are zero"),
        {"loader_imc_equals_rederived_imc": bool(np.array_equal(imc, rng_imc)),
         "loader_flags_equal_inventory": bool(np.array_equal(prl, pass_reco[imc])
                                              and np.array_equal(pgl_, pass_truth[imc])),
         **units})
    del reco, gen, reco_evt, gen_evt, mc
    gc.collect()

    # module resolution note: the files the hardcoded production root would have supplied
    if args.production_root is not None:
        prod = args.production_root.resolve()
        rel = ["omnifold_nn/omnifold/__init__.py", "omnifold_nn/omnifold/omnifold.py",
               "omnifold_nn/omnifold/dataloader.py", "omnifold_nn/omnifold/net.py",
               "omnifold_nn/omnifold/utils.py", "nd-unfolding/pet/annealed_estimator.py",
               "nd-unfolding/pet/fullevent_fps_dataloader.py",
               "nd-unfolding/pet/train_fullevent_nominal.py",
               "nd-unfolding/pet/closure_powered_truth_reweight.py"]
        same = {}
        for r in rel:
            a, b = prod / r, root / r
            same[r] = {"production": sha256(a) if a.exists() else None,
                       "pinned_68cf9d29": sha256(b) if b.exists() else None,
                       "production_mtime_utc": (time.strftime("%Y-%m-%dT%H:%M:%SZ",
                                                              time.gmtime(a.stat().st_mtime))
                                                if a.exists() else None)}
            same[r]["identical"] = same[r]["production"] == same[r]["pinned_68cf9d29"]
        checks["engine_files_on_the_hardcoded_root"] = verdict(
            "OBSERVATION",
            ("fullevent_fps_dataloader.py:57-60 and train_fullevent_nominal.py:36-39 insert the "
             "hardcoded /pscratch/.../MINERvA-OmniFold paths at sys.path[0]; by that order the "
             "historical tasks would resolve `omnifold` (MultiFold, DataLoader, PET) and "
             "`annealed_estimator` there, not in the pinned checkout. Which file actually loaded "
             "is NOT established (no runtime capture); this records whether it could matter"),
            {"files": same})

    part2 = {"scope": "Phase A2 Part 2: the data path (scope section 5, A5)",
             "inputs": {k: inputs[k] for k in ("closure_npz", "identity_sidecar",
                                               "inventory_receipt", "theirs_join_sig_npz",
                                               "theirs_join_sig_json", "theirs_cache_final")},
             "checks": checks,
             "seconds": time.time() - t0}
    write(args.outdir, "recompute_data_path.json", part2)
    print(f"[a2] done in {time.time() - t0:.0f}s", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
