# s5c second CPU lane while construction is HELD (review-3-disposition.json): Tier-S validation claims
# only, 32 lines per node; it takes the slot construction allocation 58857523 frees.
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
bash "$S5C_DEPLOY/nd-unfolding/s5c_valid_next.sh" "$S5C_DEPLOY" "$S5C_PIN" cpu
