"""Frozen-candidate configs and run manifests for the study's later stages (bank draws).

A frozen candidate = a `dev/make_dev_configs.py` candidate id plus a fixed iteration count K
(the scored iteration(s) are declared in the freeze amendment, not here). For each (stage,
replicate) every candidate gets the SAME estimator seed (paired design), derived from the stage and
replicate; the events are the study runner's bank draw `BANK:<bank>:<stage>:<rep>` (pseudodata
from the bank, prior from DEV; PROTOCOL-20260925 section 3). Coverage rows add
`--bootstrap-member b --bootstrap-seed <seed>` (section 9).

    python make_stage_manifests.py --stage S3P --bank DEV --replicates 0-3 \
        --candidates H2S1:4 CTLref:3 Cref:3 --cases dev D1_m0.350 D4c_p_up \
        --manifest runs/s3p.tsv
"""
from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
STUDY = HERE.parent
sys.path.insert(0, str(STUDY / "dev"))
import make_dev_configs as mdc  # noqa: E402

SEED_SALT = "pet-final-design-20260925-seed"
BOOT_SALT = "pet-final-design-20260925-bootstrap"


def seed_for(stage: str, rep: int, tag: str = "") -> int:
    key = f"{SEED_SALT}/{stage}/{int(rep)}" + (f"/{tag}" if tag else "")
    h = hashlib.sha256(key.encode()).digest()
    return int.from_bytes(h[:4], "big") % (2 ** 31 - 1) + 1


def boot_seed_for(stage: str, rep: int) -> int:
    h = hashlib.sha256(f"{BOOT_SALT}/{stage}/{int(rep)}".encode()).digest()
    return int.from_bytes(h[:4], "big") % (2 ** 31 - 1) + 1


def parse_reps(spec: str) -> list[int]:
    out: list[int] = []
    for part in spec.split(","):
        a, _, b = part.partition("-")
        out.extend(range(int(a), int(b or a) + 1))
    return out


def build(stage: str, bank: str, reps: list[int], cands: list[tuple[str, int]], cases: list[str],
          members: list[int] | None, out_dir: Path, manifest: Path, seed_tag: str = "") -> int:
    base = mdc.base_config()
    cfg_dir = out_dir / stage
    cfg_dir.mkdir(parents=True, exist_ok=True)
    rows = ["# name\tconfig\tconfig_hash\tselection\tdistortion\treference_run\textra_driver_args"]
    for case in cases:
        tag = "" if case == "dev" else f"-{case.replace('+', '_')}"
        for r in reps:
            seed = seed_for(stage, r, seed_tag)
            for cid, k in cands:
                desc, transform, miss = mdc.CANDIDATES[cid]
                stag = f"-s{seed_tag}" if seed_tag else ""
                name0 = f"{stage}-{cid}K{k}-{bank}{r}{tag}{stag}"
                cfg = transform(base).replace(iterations=int(k))
                note = (f"{stage}: {cid} = {desc}; K={k}; bank {bank} draw {stage}:{r}; seed {seed}; "
                        "generated by final_design/freeze/make_stage_manifests.py")
                cfg = mdc.freeze_runs.reseed(cfg, seed, name0, note)
                (cfg_dir / f"{name0}.json").write_text(cfg.to_json(indent=1) + "\n")
                rel = f"../../../final_design/configs/{stage}/{name0}.json"
                for b in (members if members is not None else [None]):
                    name = name0 if b is None else f"{name0}-b{b}"
                    extra = f"--step2-miss-mode {miss}"
                    if b is not None:
                        extra += f" --bootstrap-member {b} --bootstrap-seed {boot_seed_for(stage, r)}"
                    rows.append("\t".join([name, rel, cfg.content_hash(), f"BANK:{bank}:{stage}:{r}",
                                           case, "-", extra]))
    manifest.parent.mkdir(parents=True, exist_ok=True)
    manifest.write_text("\n".join(rows) + "\n")
    return len(rows) - 1


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--stage", required=True)
    ap.add_argument("--bank", required=True, choices=("DEV", "FB", "RB"))
    ap.add_argument("--replicates", required=True)
    ap.add_argument("--candidates", nargs="+", required=True, help="ID:K")
    ap.add_argument("--cases", nargs="+", required=True)
    ap.add_argument("--bootstrap-members", default=None, help="e.g. 1-6")
    ap.add_argument("--seed-tag", default="",
                    help="vary only the estimator seed (same bank draw): N2 seed-spread runs")
    ap.add_argument("--out-dir", type=Path, default=STUDY / "configs")
    ap.add_argument("--manifest", type=Path, required=True)
    a = ap.parse_args(argv)
    cands = [(c.split(":")[0], int(c.split(":")[1])) for c in a.candidates]
    for cid, _ in cands:
        if cid not in mdc.CANDIDATES:
            raise SystemExit(f"unknown candidate {cid}")
    members = parse_reps(a.bootstrap_members) if a.bootstrap_members else None
    n = build(a.stage, a.bank, parse_reps(a.replicates), cands, a.cases, members, a.out_dir,
              a.manifest, a.seed_tag)
    print(f"{n} runs -> {a.manifest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
