#!/usr/bin/env python3
"""Generate and validate the bounded current-work and active-playbook surfaces.

Humans declare ranking, ownership, and active lessons. Explicit leading OI state language is classified
by checked-in ordered rules with a safe-active default. This program inventories every source record,
resolves unassigned ownership, ranks promoted leaves, renders backlog/overflow, and promotes playbook
rules. It never edits OPEN_ITEMS.md or FINDINGS.md.

Default / --check: compare generated bytes with tracked outputs.
--write: rewrite generated outputs.
--coverage-report: report source-record migration coverage without changing files.
--entrypoint-report: measure the two platform bootstrap documents.
--adoption-check: additionally require full-registry coverage and canonical-adoption approval.
--self-test: exercise ranking, cap overflow, owner escalation, and playbook retirement.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
import sys
import tempfile
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
CONTROL = REPO / "docs/orchestration/control-plane"
POLICY = CONTROL / "policy.json"
OWNERS = CONTROL / "owners.tsv"
WORK_ITEMS = CONTROL / "work-items.tsv"
PLAYBOOK_SOURCE = CONTROL / "playbook.tsv"
SOURCE_INVENTORY = CONTROL / "source-record-inventory.tsv"
CURRENT = REPO / "docs/CURRENT_WORK.md"
OVERFLOW = REPO / "docs/CURRENT_WORK_OVERFLOW.md"
BACKLOG = REPO / "docs/CURRENT_WORK_BACKLOG.md"
PLAYBOOK = REPO / "docs/orchestration/PLAYBOOK.md"
OPEN_ITEMS = REPO / "docs/OPEN_ITEMS.md"
FINDINGS = REPO / "docs/orchestration/FINDINGS.md"
AGENTS = REPO / "AGENTS.md"
CLAUDE = REPO / "CLAUDE.md"
ENTRYPOINTS = (CLAUDE, AGENTS)

OWNER_COLUMNS = ("owner_id", "display_name", "accountable_holder", "escalation", "assignment_state")
WORK_COLUMNS = ("item", "source_record", "queue_override", "owner_id", "impact", "urgency",
                "next_action", "evidence")
INVENTORY_COLUMNS = ("source_record", "lifecycle", "queue", "classification_rule",
                     "source_row_sha256", "state_prefix")
PLAYBOOK_COLUMNS = ("key", "state", "operating_rule", "observable_check", "evidence",
                    "retirement_reason")
ALLOWED_QUEUES = {"NOW", "WAITING-JOSEPH", "BLOCKED-EXTERNAL"}
ALLOWED_STATES = {"active", "deferred", "retired"}


@dataclass(frozen=True)
class WorkRow:
    item: str
    queue: str
    owner: str
    action: str
    evidence: str
    basis: str
    score: int


@dataclass(frozen=True)
class SourceRecord:
    key: str
    lifecycle: str
    queue: str
    rule: str
    row_sha256: str
    state_prefix: str


def read_tsv(path: Path, columns: tuple[str, ...]) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        if tuple(reader.fieldnames or ()) != columns:
            raise ValueError(f"{path}: columns {reader.fieldnames!r}, expected {list(columns)!r}")
        return [{key: (value or "").strip() for key, value in row.items()} for row in reader]


def natural_item_key(item: str) -> tuple[int, str]:
    match = re.fullmatch(r"OI-(\d+)(?:\(([a-z])\))?", item)
    if not match:
        raise ValueError(f"invalid item key {item!r}; expected OI-N or OI-N(a)")
    return int(match.group(1)), match.group(2) or ""


def parent_item(item: str) -> str:
    match = re.match(r"OI-\d+", item)
    if not match:
        raise ValueError(f"invalid item key {item!r}")
    return match.group(0)


def source_oi_rows(path: Path) -> list[tuple[str, str, str]]:
    """Return (occurrence-key, state-prefix, exact-row) without pretending malformed Markdown is CSV."""
    matches: list[tuple[str, str, str]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        match = re.match(r"^\|\s*(OI-\d+)\s*\|\s*(.*?)\s*\|", line)
        if match:
            matches.append((match.group(1), match.group(2), line))
    totals = Counter(item for item, _, _ in matches)
    seen: Counter[str] = Counter()
    records: list[tuple[str, str, str]] = []
    for item, state, line in matches:
        seen[item] += 1
        key = f"{item}#{seen[item]}" if totals[item] > 1 else item
        records.append((key, state, line))
    return records


def source_oi_records(path: Path) -> list[str]:
    return [key for key, _, _ in source_oi_rows(path)]


def normalize_state(state: str) -> str:
    return re.sub(r"\s+", " ", re.sub(r"[*`~]", "", state)).strip().upper()


def classify_source_records(path: Path, policy: dict) -> list[SourceRecord]:
    config = policy["source_classification"]
    overrides = config.get("overrides", {})
    rules = config["ordered_rules"]
    default = config["default"]
    records: list[SourceRecord] = []
    for key, state, exact_row in source_oi_rows(path):
        base = key.split("#", 1)[0]
        decision = overrides.get(key, overrides.get(base))
        if decision is None:
            normalized = normalize_state(state)
            decision = next((rule for rule in rules if re.search(rule["pattern"], normalized)), default)
        lifecycle, queue = decision["lifecycle"], decision["queue"]
        rule = decision.get("rule", decision.get("name", "unnamed-rule"))
        prefix = re.sub(r"\s+", " ", re.sub(r"[*`~]", "", state)).strip()[:120].rstrip()
        records.append(SourceRecord(key, lifecycle, queue, rule,
                                    hashlib.sha256(exact_row.encode()).hexdigest(), prefix))
    return records


def render_inventory(records: list[SourceRecord]) -> str:
    lines = ["\t".join(INVENTORY_COLUMNS)]
    for row in records:
        values = (row.key, row.lifecycle, row.queue, row.rule, row.row_sha256, row.state_prefix)
        lines.append("\t".join(values))
    return "\n".join(lines) + "\n"


def source_ben_ids(paths: tuple[Path, ...]) -> set[str]:
    text = "\n".join(path.read_text(encoding="utf-8") for path in paths)
    return set(re.findall(r"^\|\s*(BEN-\d{3})\s*\|", text, re.MULTILINE))


def load_model(policy_path: Path = POLICY, owners_path: Path = OWNERS,
               work_path: Path = WORK_ITEMS, playbook_path: Path = PLAYBOOK_SOURCE,
               open_items_path: Path = OPEN_ITEMS,
               findings_paths: tuple[Path, ...] = (FINDINGS,)):
    errors: list[str] = []
    policy = json.loads(policy_path.read_text(encoding="utf-8"))
    owner_rows = read_tsv(owners_path, OWNER_COLUMNS)
    work_rows = read_tsv(work_path, WORK_COLUMNS)
    playbook_rows = read_tsv(playbook_path, PLAYBOOK_COLUMNS)
    source_records = classify_source_records(open_items_path, policy)
    record_by_key = {record.key: record for record in source_records}
    oi_record_set = set(record_by_key)
    oi_ids = {record.split("#", 1)[0] for record in oi_record_set}
    ben_ids = source_ben_ids(findings_paths)

    classification = policy["source_classification"]
    decisions = list(classification["ordered_rules"]) + [classification["default"]]
    decisions += list(classification.get("overrides", {}).values())
    for decision in decisions:
        if decision.get("lifecycle") not in ALLOWED_STATES:
            errors.append(f"classification decision {decision.get('name', decision.get('rule'))!r} "
                          "has invalid lifecycle")
        if decision.get("queue") not in ALLOWED_QUEUES | {"-"}:
            errors.append(f"classification decision {decision.get('name', decision.get('rule'))!r} "
                          "has invalid queue")
    for key in classification.get("overrides", {}):
        if key not in oi_record_set and key.split("#", 1)[0] not in oi_ids:
            errors.append(f"classification override targets missing source record {key}")
    for rule in classification["ordered_rules"]:
        try:
            re.compile(rule["pattern"])
        except re.error as exc:
            errors.append(f"classification rule {rule.get('name')!r} has invalid regex: {exc}")
    for record in source_records:
        if record.lifecycle not in ALLOWED_STATES:
            errors.append(f"{record.key}: classification produced invalid lifecycle {record.lifecycle!r}")
        if record.lifecycle == "active" and record.queue not in ALLOWED_QUEUES:
            errors.append(f"{record.key}: active classification has invalid queue {record.queue!r}")
        if record.lifecycle != "active" and record.queue != "-":
            errors.append(f"{record.key}: inactive classification must use queue '-'")

    owners: dict[str, dict[str, str]] = {}
    for row in owner_rows:
        oid = row["owner_id"]
        if not oid or oid in owners:
            errors.append(f"duplicate or empty owner_id: {oid!r}")
            continue
        if row["assignment_state"] not in {"assigned", "unassigned"}:
            errors.append(f"{oid}: assignment_state must be assigned/unassigned")
        if row["assignment_state"] == "assigned" and row["accountable_holder"] in {"", "-"}:
            errors.append(f"{oid}: assigned role has no accountable_holder")
        if row["assignment_state"] == "unassigned" and row["escalation"] in {"", "-"}:
            errors.append(f"{oid}: unassigned role has no escalation")
        owners[oid] = row

    seen_items: set[str] = set()
    registered_records: set[str] = set()
    active: list[WorkRow] = []
    for row in work_rows:
        item = row["item"]
        try:
            natural_item_key(item)
        except ValueError as exc:
            errors.append(str(exc))
            continue
        if item in seen_items:
            errors.append(f"duplicate work item: {item}")
        seen_items.add(item)
        source_record = row["source_record"]
        if not re.fullmatch(r"OI-\d+(?:#[1-9]\d*)?", source_record):
            errors.append(f"{item}: invalid source_record {source_record!r}")
        elif source_record not in oi_record_set:
            errors.append(f"{item}: source_record {source_record!r} is absent from OPEN_ITEMS.md")
        elif source_record.split("#", 1)[0] != parent_item(item):
            errors.append(f"{item}: source_record {source_record!r} has a different parent id")
        registered_records.add(source_record)
        if parent_item(item) not in oi_ids:
            errors.append(f"{item}: no parent row in OPEN_ITEMS.md")
        owner = owners.get(row["owner_id"])
        if owner is None:
            errors.append(f"{item}: unknown owner_id {row['owner_id']!r}")
            continue
        source = record_by_key.get(source_record)
        if source is None:
            continue
        if source.lifecycle != "active":
            errors.append(f"{item}: promoted leaf points to {source.lifecycle} source {source_record}")
            continue
        override = row["queue_override"]
        if override not in ALLOWED_QUEUES | {"-"}:
            errors.append(f"{item}: invalid queue_override {override!r}")
            continue
        queue = source.queue if override == "-" else override
        impact = row["impact"]
        urgency = row["urgency"]
        if impact not in policy["impact_weights"]:
            errors.append(f"{item}: invalid impact {impact!r}")
            continue
        if urgency not in policy["urgency_weights"]:
            errors.append(f"{item}: invalid urgency {urgency!r}")
            continue
        action = row["next_action"]
        if not action or len(action) > 260:
            errors.append(f"{item}: next_action must be 1-260 characters")
        if "OPEN_ITEMS.md" not in row["evidence"]:
            errors.append(f"{item}: evidence must route to OPEN_ITEMS.md")
        if owner["assignment_state"] == "unassigned":
            queue = policy["unassigned_owner_queue"]
            if action:
                action = policy["unassigned_action_prefix"] + action[0].lower() + action[1:]
            owner_display = f"{owner['display_name']} → {owner['escalation']}"
        else:
            owner_display = owner["display_name"]
        score = (policy["impact_weights"][impact] + policy["urgency_weights"][urgency]
                 + policy["queue_weights"][queue])
        active.append(WorkRow(item, queue, owner_display, action, row["evidence"],
                              f"{impact}/{urgency}", score))

    seen_pb: set[str] = set()
    active_pb: list[dict[str, str]] = []
    inactive_pb: list[dict[str, str]] = []
    for row in playbook_rows:
        key = row["key"]
        if not re.fullmatch(r"PB-\d{2}", key):
            errors.append(f"invalid playbook key: {key!r}")
        if key in seen_pb:
            errors.append(f"duplicate playbook key: {key}")
        seen_pb.add(key)
        if row["state"] not in {"active", "retired"}:
            errors.append(f"{key}: state must be active/retired")
            continue
        cited = re.findall(r"BEN-\d{3}", row["evidence"])
        if not cited:
            errors.append(f"{key}: cites no BEN evidence")
        for ben in cited:
            if ben not in ben_ids:
                errors.append(f"{key}: cites missing {ben}")
        if not row["operating_rule"] or not row["observable_check"]:
            errors.append(f"{key}: rule and observable_check are required")
        if row["state"] == "active":
            active_pb.append(row)
        else:
            if row["retirement_reason"] in {"", "-"}:
                errors.append(f"{key}: retired rule needs retirement_reason")
            inactive_pb.append(row)

    active.sort(key=lambda row: (-row.score, natural_item_key(row.item)))
    active_pb.sort(key=lambda row: int(row["key"].split("-")[1]))
    minimum, cap = policy["current_work_min"], policy["current_work_cap"]
    if len(active) < minimum:
        errors.append(f"active work has {len(active)} rows; minimum is {minimum}")
    if not policy["playbook_min"] <= len(active_pb) <= policy["playbook_cap"]:
        errors.append(f"active playbook has {len(active_pb)} rows; allowed range is "
                      f"{policy['playbook_min']}-{policy['playbook_cap']}")
    selected, overflow = active[:cap], active[cap:]
    unpromoted = [record for record in source_records
                  if record.lifecycle == "active" and record.key not in registered_records]
    return policy, selected, overflow, active_pb, inactive_pb, source_records, unpromoted, errors


def render_current(policy: dict, selected: list[WorkRow]) -> str:
    mode = "CANONICAL" if policy.get("canonical_adoption_allowed") else "PROTOTYPE"
    lines = [
        "# Current work — bounded attention queue", "",
        f"> **{mode}; GENERATED by `docs/orchestration/control_plane_lint.py --write`. Do not hand-edit.**",
        "> Sources: `control-plane/policy.json`, `owners.tsv`, and `work-items.tsv`. Full scientific",
        "> state and evidence remain in `docs/OPEN_ITEMS.md`; this view is authoritative only for routing.", "",
        f"Policy selects the top {policy['current_work_cap']} promoted leaves by impact, urgency,",
        "and effective queue. Unassigned roles are automatically routed to `WAITING-JOSEPH`. Ties use",
        "numeric OI id and sub-item. Source lifecycle and queue are derived from explicit OI state",
        "language; terminal and deferred records never enter this page.", "",
        "| item | queue | accountable owner | basis | next action | evidence route |",
        "|---|---|---|---|---|---|",
    ]
    for row in selected:
        lines.append(f"| {row.item} | {row.queue} | {row.owner} | {row.basis} | {row.action} | {row.evidence} |")
    lines += ["", "## Machine-enforced contract", "",
              f"- Rendered membership is capped at {policy['current_work_cap']}; overflow is generated at "
              "`docs/CURRENT_WORK_OVERFLOW.md`.",
              "- An unassigned owner cannot render as `NOW`.",
              "- Queue order and tie-breaking come only from the checked-in policy, never table position.",
              "- `policy.json` classifies explicit source state; humans declare only promotion, impact,",
              "  urgency, and accountability in `work-items.tsv`."]
    return "\n".join(lines) + "\n"


def render_overflow(policy: dict, overflow: list[WorkRow]) -> str:
    lines = ["# Current-work overflow", "",
             "> GENERATED by `docs/orchestration/control_plane_lint.py --write`. Do not hand-edit.", "",
             f"Items below were eligible but fell below the top-{policy['current_work_cap']} cutoff. "
             "They are not terminal and are not silently deferred.", "",
             "| item | effective queue | owner | basis | score | evidence |",
             "|---|---|---|---|---:|---|"]
    if overflow:
        for row in overflow:
            lines.append(f"| {row.item} | {row.queue} | {row.owner} | {row.basis} | {row.score} | {row.evidence} |")
    else:
        lines.append("| — | — | — | — | — | No eligible item currently falls below the cap. |")
    return "\n".join(lines) + "\n"


def render_backlog(records: list[SourceRecord]) -> str:
    lines = ["# Unpromoted open-item backlog", "",
             "> GENERATED by `docs/orchestration/control_plane_lint.py --write`. Do not hand-edit.", "",
             "These source records classify as active but have no promoted actionable leaf. They remain",
             "visible here and in `OPEN_ITEMS.md`; omission from `CURRENT_WORK.md` is not retirement.", "",
             "| source record | derived queue | classification rule | source state prefix |",
             "|---|---|---|---|"]
    if records:
        for row in records:
            prefix = row.state_prefix.replace("|", "\\|")
            lines.append(f"| {row.key} | {row.queue} | {row.rule} | {prefix} |")
    else:
        lines.append("| — | — | — | Every active source record has a promoted leaf. |")
    return "\n".join(lines) + "\n"


def render_playbook(policy: dict, rows: list[dict[str, str]]) -> str:
    mode = "CANONICAL" if policy.get("canonical_adoption_allowed") else "PROTOTYPE"
    lines = ["# Active campaign playbook", "",
             f"> **{mode}; GENERATED by `docs/orchestration/control_plane_lint.py --write`. Do not hand-edit.**",
             "> Source: `control-plane/playbook.tsv`. `FINDINGS.md` remains the evidence casebook and is",
             "> opened on demand by BEN id.", "",
             "| key | operating rule | executable or observable check | evidence |",
             "|---|---|---|---|"]
    for row in rows:
        lines.append(f"| {row['key']} | {row['operating_rule']} | {row['observable_check']} | {row['evidence']} |")
    lines += ["", "## Promotion and retirement", "",
              "- Search the casebook first; a new BEN must change a check, rule, or established scope.",
              f"- At most {policy['playbook_cap']} rules may be active. Promoting another rule at the cap "
              "requires retiring or consolidating one in the same source change.",
              "- Retirement preserves the TSV row, BEN evidence, and a non-empty reason; it removes only",
              "  default-read status, not history."]
    return "\n".join(lines) + "\n"


def generated_outputs(**paths) -> tuple[dict[Path, str], list[str], dict]:
    policy, selected, overflow, playbook, _, source_records, unpromoted, errors = load_model(**paths)
    outputs = {CURRENT: render_current(policy, selected),
               OVERFLOW: render_overflow(policy, overflow),
               BACKLOG: render_backlog(unpromoted),
               SOURCE_INVENTORY: render_inventory(source_records),
               PLAYBOOK: render_playbook(policy, playbook)}
    return outputs, errors, policy


def registry_coverage(open_items_path: Path = OPEN_ITEMS,
                      work_path: Path = WORK_ITEMS) -> tuple[int, int, int, Counter]:
    policy = json.loads(POLICY.read_text(encoding="utf-8"))
    records = classify_source_records(open_items_path, policy)
    promoted = {row["source_record"] for row in read_tsv(work_path, WORK_COLUMNS)}
    active = {record.key for record in records if record.lifecycle == "active"}
    counts = Counter((record.lifecycle, record.queue) for record in records)
    return len(records), len(promoted), len(active - promoted), counts


def adoption_errors(policy: dict) -> list[str]:
    errors = []
    if not policy.get("canonical_adoption_allowed"):
        errors.append("canonical adoption is disabled in policy.json")
    if policy.get("registry_scope") != "all-open-items-records":
        errors.append("registry_scope must be all-open-items-records before adoption")
    return errors


CANONICAL_CLAUDE_ROUTE = (
    "Read `AGENTS.md` before acting; it is the shared scientific front door and routes every "
    "specialized task to its governing evidence. This file is only the automatically loaded bootstrap."
)

CANONICAL_CLAUDE_BULLETS = (
    "Treat the front door and generated state as views, never evidence or authorization.",
    "Before quoting, writing, computing, or deciding a gate, open the routed canonical artifact and "
    "re-measure volatile fields.",
    "A result is live only after its evidence and required records land in a commit.",
    "Audit and review work is read-only and uses an isolated worktree; inspect status afterward.",
    "Pre-freeze provenance may leave `main` only through the pushed evidence tag, tested recovery, "
    "an exact removal-family authorization, and a surviving discovery route.",
    "Domain, environment, and scheduler rules are task-specific; follow the route in `AGENTS.md` "
    "rather than inferring them from memory.",
)

CANONICAL_INTEGRITY_RULES = (
    "This front door and generated state are views, never evidence or authorization.",
    "A result is live only after its evidence and required ledger/RUN_LOG/STATUS records land in a "
    "commit. Uncommitted or merely relayed results are not quotable.",
    "Worker agreement is not independence. Trace agreeing statements to their first measurement and "
    "count shared origins once.",
    "Generated state is a view, not truth. Run its freshness check, then observe the governing source "
    "or scheduler before acting.",
    "Audit and review work is read-only. Use isolated worktrees, inspect status afterward, and never "
    "freeze an auditor's silent edit into a receipt.",
    "Pre-freeze provenance may leave `main` only through the pushed evidence tag, tested recovery, "
    "an exact removal-family authorization, and a surviving discovery route.",
    "Domain-specific contracts live behind task routes. Do not reconstruct a pipeline from this summary.",
)


def markdown_bullets(section: str) -> tuple[list[str], bool]:
    """Return normalized bullets and whether non-bullet prose/comments were present."""
    bullets: list[str] = []
    invalid = False
    for raw in section.splitlines():
        if not raw.strip():
            continue
        if raw.startswith("- "):
            bullets.append(raw[2:].strip())
        elif raw.startswith("  ") and bullets:
            bullets[-1] += " " + raw.strip()
        else:
            invalid = True
    return bullets, invalid


def bootstrap_contract_errors(agents: str, claude: str, playbook: str) -> list[str]:
    """Validate the thin shared front door without requiring duplicated bootstrap prose."""
    errors: list[str] = []
    if len(agents.splitlines()) > 150:
        errors.append("AGENTS.md exceeds the 150-line front-door cap")
    if len(claude.splitlines()) > 20:
        errors.append("CLAUDE.md exceeds the 20-line bootstrap cap")
    for required in ("docs/CURRENT_WORK.md", "docs/orchestration/PLAYBOOK.md"):
        if required not in agents:
            errors.append(f"AGENTS.md does not route to {required}")
    claude_blocks = [block for block in re.split(r"\n\s*\n", claude)
                     if block.strip() and not block.lstrip().startswith("#")]
    claude_paragraphs = [" ".join(block.split()) for block in claude_blocks]
    if not claude_paragraphs or claude_paragraphs[0] != CANONICAL_CLAUDE_ROUTE:
        errors.append("CLAUDE.md does not begin with the exact canonical AGENTS.md route")
    claude_bullets, invalid_claude = markdown_bullets("\n\n".join(claude_blocks[1:]))
    if invalid_claude or tuple(claude_bullets) != CANONICAL_CLAUDE_BULLETS:
        errors.append("CLAUDE.md bootstrap rules do not match the canonical bullet contract")
    if claude.count("AGENTS.md") != 2:
        errors.append("CLAUDE.md must contain exactly its two canonical AGENTS.md routes")
    integrity = re.search(
        r"^## Minimal integrity rules\n(.*?)(?=^## )", agents, re.MULTILINE | re.DOTALL)
    if not integrity:
        errors.append("AGENTS.md has no bounded Minimal integrity rules section")
    integrity_text = integrity.group(1) if integrity else ""
    integrity_bullets, invalid_integrity = markdown_bullets(integrity_text)
    if invalid_integrity or tuple(integrity_bullets) != CANONICAL_INTEGRITY_RULES:
        errors.append("AGENTS.md Minimal integrity rules do not match the canonical bullet contract")
    active_bens = set(re.findall(r"BEN-\d{3}", playbook))
    duplicated_bens = sorted(active_bens & set(re.findall(
        r"BEN-\d{3}", integrity_text)))
    if duplicated_bens:
        errors.append("AGENTS.md duplicates BEN-backed playbook rules in Minimal integrity rules: "
                      + ", ".join(duplicated_bens))
    return errors


def check_or_write(write: bool, adoption: bool = False) -> int:
    outputs, errors, policy = generated_outputs()
    if adoption:
        errors.extend(adoption_errors(policy))
    for path, expected in outputs.items():
        if write:
            path.write_text(expected, encoding="utf-8")
        elif not path.exists() or path.read_text(encoding="utf-8") != expected:
            errors.append(f"generated output stale: {path.relative_to(REPO)}; run --write")
    errors.extend(bootstrap_contract_errors(
        AGENTS.read_text(encoding="utf-8"), CLAUDE.read_text(encoding="utf-8"), outputs[PLAYBOOK]))
    catalog = (REPO / "docs/orchestration/CATALOG.md").read_text(encoding="utf-8")
    for required in ("CURRENT_WORK.md", "CURRENT_WORK_OVERFLOW.md", "CURRENT_WORK_BACKLOG.md",
                     "PLAYBOOK.md", "control-plane/policy.json", "source-record-inventory.tsv"):
        if required not in catalog:
            errors.append(f"CATALOG.md does not route to {required}")
    if errors:
        for error in errors:
            print(f"CONTROL-PLANE FAIL: {error}")
        return 1
    verb = "WROTE" if write else "PASS"
    selected = len(re.findall(r"^\| OI-", outputs[CURRENT], re.MULTILINE))
    overflow = len(re.findall(r"^\| OI-", outputs[OVERFLOW], re.MULTILINE))
    backlog = len(re.findall(r"^\| OI-", outputs[BACKLOG], re.MULTILINE))
    active_pb = len(re.findall(r"^\| PB-", outputs[PLAYBOOK], re.MULTILINE))
    inventory = len(outputs[SOURCE_INVENTORY].splitlines()) - 1
    print(f"CONTROL-PLANE {verb}: {selected} selected; {overflow} overflow; {backlog} backlog; "
          f"{inventory} source records; {active_pb} playbook rules")
    return 0


def self_test() -> int:
    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        policy = json.loads(POLICY.read_text())
        policy.update({"current_work_min": 1, "current_work_cap": 2,
                       "playbook_min": 1, "playbook_cap": 2})
        policy["source_classification"]["overrides"] = {}
        (root / "policy.json").write_text(json.dumps(policy))
        (root / "owners.tsv").write_text(
            "\t".join(OWNER_COLUMNS) + "\n"
            "held\tHeld\tLane H\tJoseph\tassigned\n"
            "vacant\tVacant\t-\tJoseph\tunassigned\n")
        (root / "OPEN_ITEMS.md").write_text(
            "| OI-1 | OPEN | x | x | x |\n| OI-2 | OPEN | x | x | x |\n| OI-3 | OPEN | x | x | x |\n")
        (root / "FINDINGS.md").write_text("| BEN-001 | x | x | x |\n| BEN-002 | x | x | x |\n")
        (root / "work.tsv").write_text(
            "\t".join(WORK_COLUMNS) + "\n"
            "OI-1\tOI-1\t-\theld\tmaintenance\tP3\tact one\tdocs/OPEN_ITEMS.md OI-1\n"
            "OI-2\tOI-2\t-\tvacant\tpublication\tP0\tact two\tdocs/OPEN_ITEMS.md OI-2\n"
            "OI-3\tOI-3\t-\theld\tsafety\tP1\tact three\tdocs/OPEN_ITEMS.md OI-3\n")
        (root / "play.tsv").write_text(
            "\t".join(PLAYBOOK_COLUMNS) + "\n"
            "PB-01\tactive\trule\tcheck\tBEN-001\t-\n"
            "PB-02\tretired\told rule\told check\tBEN-002\tconsolidated into PB-01\n")
        loaded = load_model(root / "policy.json", root / "owners.tsv", root / "work.tsv",
                            root / "play.tsv", root / "OPEN_ITEMS.md", (root / "FINDINGS.md",))
        _, selected, overflow, active_pb, inactive_pb, source_records, unpromoted, errors = loaded
        duplicate_fixture = root / "OPEN_ITEMS-duplicates.md"
        duplicate_fixture.write_text(
            "| OI-1 | OPEN | x | x | x |\n| OI-1 | CLOSED | x | x | x |\n"
            "| OI-2 | OPEN | x | x | x |\n")
        classification_fixture = root / "OPEN_ITEMS-classification.md"
        classification_fixture.write_text(
            "| OI-10 | CLOSED 2026-08-18 | x |\n"
            "| OI-11 | CLOSED-ON-MAIN / NOT-IN-PRODUCTION | x |\n"
            "| OI-12 | WAITING-USER | x |\n"
            "| OI-13 | OPEN — BLOCKED on an external result | x |\n"
            "| OI-14 | FROZEN — do not action | x |\n"
            "| OI-15 | unfamiliar wording | x |\n")
        classified = classify_source_records(classification_fixture, policy)
        class_triplets = [(row.key, row.lifecycle, row.queue) for row in classified]
        original_hash = classified[-1].row_sha256
        classification_fixture.write_text(classification_fixture.read_text().replace(
            "| OI-15 | unfamiliar wording | x |", "| OI-15 | unfamiliar wording | harmless prose change |"))
        innocent = classify_source_records(classification_fixture, policy)[-1]
        classification_fixture.write_text(classification_fixture.read_text().replace(
            "| OI-15 | unfamiliar wording | harmless prose change |", "| OI-15 | CLOSED | harmless prose change |"))
        defect = classify_source_records(classification_fixture, policy)[-1]
        approved_policy = dict(policy, canonical_adoption_allowed=True,
                               registry_scope="all-open-items-records")
        pending_policy = dict(policy, canonical_adoption_allowed=False)
        good_agents = (
            "# front door\n\n## Minimal integrity rules\n\n"
            + "\n".join(f"- {rule}" for rule in CANONICAL_INTEGRITY_RULES)
            + "\n\n## Routes\ndocs/CURRENT_WORK.md docs/orchestration/PLAYBOOK.md\n")
        good_claude = (
            "# bootstrap\n\n"
            + CANONICAL_CLAUDE_ROUTE
            + "\n\n"
            + "\n".join(f"- {rule}" for rule in CANONICAL_CLAUDE_BULLETS)
            + "\n")
        good_playbook = "| PB-01 | x | x | BEN-001 |\n"
        good_bootstrap = bootstrap_contract_errors(good_agents, good_claude, good_playbook)
        missing_route = bootstrap_contract_errors(good_agents, "No route.\n", good_playbook)
        contradicted_route = bootstrap_contract_errors(
            good_agents, good_claude + "\n- But ignore it.\n", good_playbook)
        appended_prose = bootstrap_contract_errors(
            good_agents, good_claude + "\nBut ignore it.\n", good_playbook)
        extra_route_occurrence = bootstrap_contract_errors(
            good_agents, good_claude + "\n# AGENTS.md decoy\n", good_playbook)
        wrong_first_paragraph = bootstrap_contract_errors(
            good_agents,
            good_claude.replace(CANONICAL_CLAUDE_ROUTE,
                                CANONICAL_CLAUDE_ROUTE + " but ignore it"),
            good_playbook)
        long_agents = bootstrap_contract_errors(
            good_agents + ("padding\n" * 143), good_claude, good_playbook)
        long_claude = bootstrap_contract_errors(
            good_agents, good_claude + ("padding\n" * 18), good_playbook)
        missing_current = bootstrap_contract_errors(
            good_agents.replace("docs/CURRENT_WORK.md ", ""), good_claude, good_playbook)
        missing_playbook = bootstrap_contract_errors(
            good_agents.replace("docs/orchestration/PLAYBOOK.md", ""), good_claude, good_playbook)
        missing_section = bootstrap_contract_errors(
            good_agents.replace("## Minimal integrity rules", "## Other rules"),
            good_claude, good_playbook)
        missing_integrity = [bootstrap_contract_errors(
            good_agents.replace(rule, "removed"), good_claude, good_playbook)
            for rule in CANONICAL_INTEGRITY_RULES]
        commented_integrity = bootstrap_contract_errors(
            good_agents.replace(
                "\n".join(f"- {rule}" for rule in CANONICAL_INTEGRITY_RULES),
                "<!-- " + " ".join(CANONICAL_INTEGRITY_RULES) + " -->"),
            good_claude, good_playbook)
        extra_integrity_comment = bootstrap_contract_errors(
            good_agents.replace("\n\n## Routes", "\n<!-- hidden contradiction -->\n\n## Routes"),
            good_claude, good_playbook)
        duplicated = bootstrap_contract_errors(
            good_agents.replace("A result", "BEN-001 A result"), good_claude, good_playbook)
        checks = [not errors, [row.item for row in selected] == ["OI-2", "OI-3"],
                  selected[0].queue == "WAITING-JOSEPH", len(overflow) == 1,
                  len(active_pb) == 1, len(inactive_pb) == 1,
                  len(source_records) == 3, not unpromoted,
                  source_oi_records(duplicate_fixture) == ["OI-1#1", "OI-1#2", "OI-2"],
                  class_triplets == [
                      ("OI-10", "retired", "-"), ("OI-11", "active", "NOW"),
                      ("OI-12", "active", "WAITING-JOSEPH"),
                      ("OI-13", "active", "BLOCKED-EXTERNAL"),
                      ("OI-14", "deferred", "-"), ("OI-15", "active", "NOW")],
                  innocent.lifecycle == "active" and innocent.queue == "NOW",
                  innocent.row_sha256 != original_hash,
                  defect.lifecycle == "retired",
                  bool(adoption_errors(pending_policy)), not adoption_errors(approved_policy),
                  not good_bootstrap,
                  any("canonical AGENTS.md route" in error for error in missing_route),
                  any("canonical bullet contract" in error for error in contradicted_route),
                  any("canonical bullet contract" in error for error in appended_prose),
                  any("exactly its two" in error for error in extra_route_occurrence),
                  any("exact canonical AGENTS.md route" in error
                      for error in wrong_first_paragraph),
                  any("150-line" in error for error in long_agents),
                  any("20-line" in error for error in long_claude),
                  any("CURRENT_WORK.md" in error for error in missing_current),
                  any("PLAYBOOK.md" in error for error in missing_playbook),
                  any("no bounded" in error for error in missing_section),
                  all(any("canonical bullet contract" in error for error in result)
                      for result in missing_integrity),
                  any("canonical bullet contract" in error for error in commented_integrity),
                  any("canonical bullet contract" in error for error in extra_integrity_comment),
                  any("duplicates BEN-backed" in error for error in duplicated)]
        if not all(checks):
            print("control-plane self-test: FAIL")
            print("errors:", errors)
            print("selected:", selected, "overflow:", overflow)
            return 1
    print("control-plane self-test: PASS")
    return 0


def coverage_report() -> int:
    total, promoted, backlog, counts = registry_coverage()
    print(f"CONTROL-PLANE COVERAGE: {total}/{total} source records classified")
    print(f"promoted source records: {promoted}; active unpromoted backlog: {backlog}")
    for (lifecycle, queue), count in sorted(counts.items()):
        print(f"{lifecycle:8} {queue:16} {count}")
    return 0


def entrypoint_report() -> int:
    total = 0
    for path in ENTRYPOINTS:
        words = len(re.findall(r"\S+", path.read_text(encoding="utf-8")))
        total += words
        print(f"{words:7d}  {path.relative_to(REPO)}")
    print(f"{total:7d}  TOTAL prescribed default path")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--write", action="store_true")
    group.add_argument("--coverage-report", action="store_true")
    group.add_argument("--entrypoint-report", action="store_true")
    group.add_argument("--self-test", action="store_true")
    group.add_argument("--adoption-check", action="store_true")
    args = parser.parse_args()
    if args.self_test:
        return self_test()
    if args.coverage_report:
        return coverage_report()
    if args.entrypoint_report:
        return entrypoint_report()
    return check_or_write(args.write, args.adoption_check)


if __name__ == "__main__":
    sys.exit(main())
