#!/usr/bin/env python3
"""Generate and validate the bounded current-work and active-playbook surfaces.

Humans declare routing outright in the checked-in register `control-plane/work-items.tsv`: one row
per work item carrying lifecycle, queue, owner, artifact, action, authority, terminal criterion and
evidence route. This program validates that register, inventories every source record, resolves
unassigned ownership, ranks promoted leaves, renders backlog/overflow, and promotes playbook rules.
It never edits OPEN_ITEMS.md or FINDINGS.md.

NO CHARACTER OF `OPEN_ITEMS.md` OUTSIDE A RECORD'S `| OI-N |` ID TOKEN CAN CHANGE A LIFECYCLE OR A
QUEUE. State prose is narrative history: it is reported, digested and rendered, and it routes
nothing. A record with no register row fails the commit, so there is no permissive default to fall
through to.

Default / --check: compare generated bytes with tracked outputs.
--write: rewrite generated outputs.
--coverage-report: report source-record migration coverage without changing files.
--entrypoint-report: measure the two platform bootstrap documents.
--adoption-check: additionally require full-registry coverage and canonical-adoption approval.
--self-test: exercise ranking, cap overflow, owner escalation, and playbook retirement.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
import subprocess
import sys
import tempfile
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
CONTROL = REPO / "docs/orchestration/control-plane"
POLICY = CONTROL / "policy.json"
OWNERS = CONTROL / "owners.tsv"
WORK_ITEMS = CONTROL / "work-items.tsv"
PLAYBOOK_SOURCE = CONTROL / "playbook.tsv"
SOURCE_INVENTORY = CONTROL / "source-record-inventory.tsv"
CURRENT = REPO / "docs/CURRENT_WORK.md"
OVERFLOW = REPO / "docs/CURRENT_WORK_OVERFLOW.md"
BACKLOG = REPO / "docs/CURRENT_WORK_BACKLOG.md"
PLAYBOOK = REPO / "docs/orchestration/PLAYBOOK.md"
OPEN_ITEMS = REPO / "docs/OPEN_ITEMS.md"
FINDINGS = REPO / "docs/orchestration/FINDINGS.md"
AGENTS = REPO / "AGENTS.md"
CLAUDE = REPO / "CLAUDE.md"
LIVE_STATE = REPO / "docs/orchestration/LIVE-STATE.md"
# The prescribed default path is what AGENTS.md ROUTES as required reading, not only the two
# bootstrap files: its "Evidence routes" table sends every session to live state, the bounded
# queue, and the governing OI row before it may act. Measuring CLAUDE.md + AGENTS.md alone
# reported 1847 words for a path that is far longer, so orientation cost read as small. No
# rationale for the two-file form is recorded and the constant had one use site.
# AGENTS.md's Evidence-routes table prescribes these two ways of reading, and they are not
# interchangeable. FULL_READ is read whole by every session. ROW_ROUTED is SEARCHED: the route
# at AGENTS.md "What should happen next?" says `docs/CURRENT_WORK.md`, then **the exact cited
# row** in OPEN_ITEMS.md -- one record, not the file. Summing them under one total prices a
# corpus as if it were prescribed reading and overstates the path ~5.4x.
FULL_READ = (CLAUDE, AGENTS, LIVE_STATE, CURRENT)
ROW_ROUTED = (OPEN_ITEMS,)
ENTRYPOINTS = FULL_READ + ROW_ROUTED

OWNER_COLUMNS = ("owner_id", "display_name", "accountable_holder", "escalation", "assignment_state")
# The register replaces `queue_override`: `queue` is primary, not a correction to an inference.
REGISTER_COLUMNS = ("item", "source_record", "lifecycle", "queue", "promotion", "owner_id",
                    "impact", "urgency", "artifact", "next_action", "authority",
                    "terminal_criterion", "evidence", "state_digest")
INVENTORY_COLUMNS = ("source_record", "lifecycle", "queue", "classification_rule",
                     "source_row_sha256", "state_prefix")
PLAYBOOK_COLUMNS = ("key", "state", "operating_rule", "observable_check", "evidence",
                    "retirement_reason")
# Three of the eight declared fields have never been authored anywhere in the tree: no row has ever
# carried an artifact, an authority, or a terminal criterion. Transcribing a value nobody wrote would
# convert an absence into an apparent declaration, which is the defect this register exists to remove.
# They therefore carry this sentinel until their owner authors them, and it becomes an error when
# `policy.routing.migration_open` is turned off. `OI-73` reserves that per-row pass to the owner.
MIGRATION_SENTINEL = "migration-carried-forward"
MIGRATABLE_COLUMNS = ("artifact", "authority", "terminal_criterion")
ITEM_KEY = re.compile(r"OI-(\d+)(?:#([1-9]\d*))?(?:\(([a-z])\))?")
SOURCE_RECORD_KEY = re.compile(r"OI-\d+(?:#[1-9]\d*)?")


@dataclass(frozen=True)
class WorkRow:
    item: str
    queue: str
    owner: str
    action: str
    evidence: str
    basis: str
    score: int


@dataclass(frozen=True)
class RegisterRow:
    """One declared work item. `lifecycle` is '-' on a leaf row, which inherits its source row's.

    Keeping lifecycle on exactly one row per source record makes divergent lifecycles for the same
    record unrepresentable rather than merely lint-detected.
    """

    item: str
    source_record: str
    lifecycle: str
    queue: str
    promotion: str
    owner_id: str
    impact: str
    urgency: str
    artifact: str
    next_action: str
    authority: str
    terminal_criterion: str
    evidence: str
    state_digest: str

    @property
    def is_source_row(self) -> bool:
        return self.item == self.source_record


@dataclass(frozen=True)
class SourceRecord:
    key: str
    lifecycle: str
    queue: str
    rule: str
    row_sha256: str
    state_prefix: str
    state_digest_drifted: bool = False


def read_tsv(path: Path, columns: tuple[str, ...]) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        if tuple(reader.fieldnames or ()) != columns:
            raise ValueError(f"{path}: columns {reader.fieldnames!r}, expected {list(columns)!r}")
        return [{key: (value or "").strip() for key, value in row.items()} for row in reader]


def natural_item_key(item: str) -> tuple[int, int, str]:
    """Sort key for an item id.

    The occurrence suffix is required because two waived id collisions (`OI-64`, `OI-65`) give
    `source_oi_rows` the keys `OI-64#1`/`OI-64#2`, and every source record now needs a register row.
    Unsuffixed items sort at occurrence 0, so the existing tie-break order is unchanged.
    """
    match = ITEM_KEY.fullmatch(item)
    if not match:
        raise ValueError(f"invalid item key {item!r}; expected OI-N, OI-N#k or OI-N(a)")
    return int(match.group(1)), int(match.group(2) or 0), match.group(3) or ""


def source_oi_rows(path: Path) -> list[tuple[str, str, str]]:
    """Return (occurrence-key, state-prefix, exact-row) without pretending malformed Markdown is CSV."""
    matches: list[tuple[str, str, str]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        match = re.match(r"^\|\s*(OI-\d+)\s*\|\s*(.*?)\s*\|", line)
        if match:
            matches.append((match.group(1), match.group(2), line))
    totals = Counter(item for item, _, _ in matches)
    seen: Counter[str] = Counter()
    records: list[tuple[str, str, str]] = []
    for item, state, line in matches:
        seen[item] += 1
        key = f"{item}#{seen[item]}" if totals[item] > 1 else item
        records.append((key, state, line))
    return records


def source_oi_records(path: Path) -> list[str]:
    return [key for key, _, _ in source_oi_rows(path)]


def state_cell_digest(state: str) -> str:
    """Digest of a state cell with markup and whitespace normalized away.

    Report-only. It detects that the narrative a declaration was made against has since moved; it
    can never change a lifecycle or a queue, and it must never fail a commit -- appending a
    correction to an active row is this repository's normal working mode, and a guard that fires on
    every correct run is not a guard.
    """
    normalized = re.sub(r"\s+", " ", re.sub(r"[*`~]", "", state)).strip()
    return "sha256:" + hashlib.sha256(normalized.encode("utf-8")).hexdigest()


def declared_routing(path: Path, register: dict[str, RegisterRow]) -> list[SourceRecord]:
    """Return one SourceRecord per OPEN_ITEMS.md record, routed from its own declaration.

    The only thing read from a row is its `| OI-N |` id token, which says the record EXISTS. The
    state cell is digested and truncated for display and then has no further effect: there is no
    pattern, no ordered rule and no default. A record with no declaration is skipped here and
    reported by `load_register`, so absence fails the commit instead of scoring as urgent.
    """
    records: list[SourceRecord] = []
    for key, state, exact_row in source_oi_rows(path):
        row = register.get(key)
        if row is None:
            continue                            # reported by load_register as missing coverage
        rule = ("migration-carried-forward" if row.authority == MIGRATION_SENTINEL else "declared")
        prefix = re.sub(r"\s+", " ", re.sub(r"[*`~]", "", state)).strip()[:120].rstrip()
        records.append(SourceRecord(
            key, row.lifecycle, row.queue, rule,
            hashlib.sha256(exact_row.encode()).hexdigest(), prefix,
            row.state_digest not in {"-", state_cell_digest(state)}))
    return records


def render_inventory(records: list[SourceRecord]) -> str:
    lines = ["\t".join(INVENTORY_COLUMNS)]
    for row in records:
        values = (row.key, row.lifecycle, row.queue, row.rule, row.row_sha256, row.state_prefix)
        lines.append("\t".join(values))
    return "\n".join(lines) + "\n"


def tracked_paths(candidates: set[str]) -> tuple[set[str], str | None]:
    """Return the subset of `candidates` git reports as tracked, plus an unverifiable reason.

    Batched into one index read. On git failure it returns no tracked paths AND a reason, so an
    unverifiable authority is reported as unverifiable instead of silently passing or silently
    failing -- the two arms are distinguishable, which a bare empty set would not be.
    """
    if not candidates:
        return set(), None
    try:
        proc = subprocess.run(["git", "-C", str(REPO), "ls-files", "-z", "--", *sorted(candidates)],
                              capture_output=True, timeout=15, check=False)
    except (OSError, subprocess.SubprocessError) as exc:
        return set(), f"git ls-files unavailable: {exc}"
    if proc.returncode != 0:
        return set(), f"git ls-files rc={proc.returncode}"
    return {n for n in proc.stdout.decode("utf-8", "replace").split("\0") if n}, None


def _is_artifact_reference(value: str) -> bool:
    """Whether `value` names a repository path, a content digest, or a scheduler job."""
    if re.fullmatch(r"sha256:[0-9a-f]{64}", value) or re.fullmatch(r"job:\d+(?:_\d+)?", value):
        return True
    return not value.startswith("/") and (REPO / value).exists()


def _authority_errors(item: str, authority: str, tracked: set[str],
                      unverifiable_reason: str | None) -> list[str]:
    """Validate one declared authority: a tracked record, a self-filing, or an admitted absence."""
    if authority == "unassigned" or re.fullmatch(r"self-filed:\d{4}-\d{2}-\d{2}", authority):
        return []
    if "#" not in authority:
        return [f"{item}: invalid authority {authority!r}; expected <tracked-path>#<anchor>, "
                "self-filed:<YYYY-MM-DD>, or unassigned"]
    path = authority.split("#", 1)[0]
    if unverifiable_reason:
        return [f"{item}: authority path {path!r} cannot be verified ({unverifiable_reason})"]
    if path not in tracked:
        return [f"{item}: authority path {path!r} is not tracked"]
    return []


def _field_errors(row: RegisterRow, *, active: bool, policy: dict,
                  owners: dict[str, dict[str, str]], tracked: set[str],
                  unverifiable_reason: str | None, migration_open: bool) -> list[str]:
    """Validate one register row's declared fields. Reads no state prose.

    Keyword-only because six of the seven arguments would otherwise be silently swappable:
    two dicts, two flags, and a set beside an optional string.
    """
    routing = policy["routing"]
    errors: list[str] = []
    item = row.item

    def is_sentinel(column: str, value: str) -> bool:
        """Whether this field is still carrying the migration sentinel. Records the ratchet
        error as a side effect, so a closed migration reports every unreviewed field."""
        if value != MIGRATION_SENTINEL:
            return False
        if not migration_open:
            errors.append(f"{item}: {column} is {MIGRATION_SENTINEL!r} but the migration is closed; "
                          "its owner must declare a value")
        return True

    if row.owner_id not in owners:
        errors.append(f"{item}: unknown owner_id {row.owner_id!r}")
    if "OPEN_ITEMS.md" not in row.evidence:
        errors.append(f"{item}: evidence must route to OPEN_ITEMS.md")

    if not active:
        for column in ("queue", "promotion", "impact", "urgency", "artifact", "next_action",
                       "terminal_criterion"):
            if getattr(row, column) != "-":
                errors.append(f"{item}: non-active row must use '-' for {column}")
        return errors

    if row.queue not in routing["queues"]:
        errors.append(f"{item}: invalid queue {row.queue!r}")
    elif row.queue not in policy["queue_weights"]:
        errors.append(f"{item}: queue {row.queue!r} has no weight in queue_weights; a queue token "
                      "cannot be used before it is priced")
    if row.promotion not in {"promoted", "backlog"}:
        errors.append(f"{item}: active row promotion must be promoted/backlog, got "
                      f"{row.promotion!r}")
    elif row.promotion == "promoted":
        if row.impact not in policy["impact_weights"]:
            errors.append(f"{item}: invalid impact {row.impact!r}")
        if row.urgency not in policy["urgency_weights"]:
            errors.append(f"{item}: invalid urgency {row.urgency!r}")
        if row.next_action in {"", "-"} or len(row.next_action) > 260:
            errors.append(f"{item}: next_action must be 1-260 characters")
        if not is_sentinel("artifact", row.artifact) and not _is_artifact_reference(row.artifact):
            errors.append(f"{item}: artifact {row.artifact!r} is not a repo path, a "
                          "sha256:<64hex>, or a job:<id>")
    else:
        for column in ("impact", "urgency", "artifact", "next_action"):
            if getattr(row, column) != "-":
                errors.append(f"{item}: unpromoted row must use '-' for {column}; an unpromoted row "
                              "cannot carry a score a later promotion would silently inherit")

    if not is_sentinel("terminal_criterion", row.terminal_criterion):
        kind, _, body = row.terminal_criterion.partition(": ")
        if kind not in routing["terminal_criterion_kinds"] or not body.strip():
            errors.append(f"{item}: terminal_criterion must read '<kind>: <text>' with kind in "
                          f"{sorted(routing['terminal_criterion_kinds'])}, got "
                          f"{row.terminal_criterion!r}")
    if not is_sentinel("authority", row.authority):
        errors.extend(_authority_errors(item, row.authority, tracked, unverifiable_reason))
    return errors


def load_register(path: Path, policy: dict, owners: dict[str, dict[str, str]],
                  oi_records: list[str]) -> tuple[dict[str, RegisterRow], list[str]]:
    """Read and validate the declarative routing register.

    Every routing value is read from a declared column. No character of `OPEN_ITEMS.md` outside the
    `OI-N` id token reaches this function: it takes the record ids as a list of keys.

    Fail-closed coverage is the point of the whole register -- a source record with no declaration is
    an error, not a permissive default -- so `safe-default-active` has no successor to fall through to.
    """
    migration_open = bool(policy["routing"].get("migration_open"))
    rows = [RegisterRow(**row) for row in read_tsv(path, REGISTER_COLUMNS)]
    errors: list[str] = []
    by_item: dict[str, RegisterRow] = {}
    for row in rows:
        try:
            natural_item_key(row.item)
        except ValueError as exc:
            errors.append(str(exc))
            continue
        if row.item in by_item:
            errors.append(f"duplicate register row for item {row.item}")
            continue
        by_item[row.item] = row

    record_set = set(oi_records)
    source_rows = {row.source_record: row for row in by_item.values() if row.is_source_row}
    for key in oi_records:
        if key not in source_rows:
            errors.append(f"{key} has no routing declaration in {_label(path)}; "
                          "add its register row")
    candidates = {row.authority.split("#", 1)[0]
                  for row in by_item.values() if "#" in row.authority}
    tracked, unverifiable_reason = tracked_paths(candidates)

    for item, row in sorted(by_item.items(), key=lambda pair: natural_item_key(pair[0])):
        number, occurrence, _ = natural_item_key(item)
        expected = f"OI-{number}" + (f"#{occurrence}" if occurrence else "")
        if not SOURCE_RECORD_KEY.fullmatch(row.source_record):
            errors.append(f"{item}: invalid source_record {row.source_record!r}")
            continue
        if row.source_record != expected:
            errors.append(f"{item}: source_record {row.source_record!r} has a different parent id; "
                          f"item {item} belongs to {expected}")
            continue
        if row.source_record not in record_set:
            errors.append(f"{item}: source_record {row.source_record!r} is absent from "
                          "OPEN_ITEMS.md")
            continue
        source = source_rows.get(row.source_record)
        if row.is_source_row:
            if row.lifecycle not in policy["routing"]["lifecycles"]:
                errors.append(f"{item}: invalid lifecycle {row.lifecycle!r}")
                continue
            if row.state_digest != "-" and not re.fullmatch(r"sha256:[0-9a-f]{64}",
                                                            row.state_digest):
                errors.append(f"{item}: state_digest must be '-' or sha256:<64hex>")
        else:
            if row.lifecycle != "-":
                errors.append(f"{item}: leaf row must inherit lifecycle; use '-', got "
                              f"{row.lifecycle!r}")
            if row.state_digest != "-":
                errors.append(f"{item}: leaf row must use '-' for state_digest; the digest belongs "
                              "to the source row")
            if source is None:
                continue
            if source.lifecycle != "active":
                errors.append(f"{item}: promoted leaf points to {source.lifecycle} source "
                              f"{row.source_record}")
                continue
        active = (row.lifecycle if row.is_source_row else source.lifecycle) == "active"
        errors.extend(_field_errors(row, active=active, policy=policy, owners=owners,
                                    tracked=tracked, unverifiable_reason=unverifiable_reason,
                                    migration_open=migration_open))
    return by_item, errors


def source_ben_ids(paths: tuple[Path, ...]) -> set[str]:
    text = "\n".join(path.read_text(encoding="utf-8") for path in paths)
    return set(re.findall(r"^\|\s*(BEN-\d{3})\s*\|", text, re.MULTILINE))


def load_model(policy_path: Path = POLICY, owners_path: Path = OWNERS,
               work_path: Path = WORK_ITEMS, playbook_path: Path = PLAYBOOK_SOURCE,
               open_items_path: Path = OPEN_ITEMS,
               findings_paths: tuple[Path, ...] = (FINDINGS,)):
    errors: list[str] = []
    policy = json.loads(policy_path.read_text(encoding="utf-8"))
    owner_rows = read_tsv(owners_path, OWNER_COLUMNS)
    playbook_rows = read_tsv(playbook_path, PLAYBOOK_COLUMNS)
    oi_records = source_oi_records(open_items_path)
    ben_ids = source_ben_ids(findings_paths)

    owners: dict[str, dict[str, str]] = {}
    for row in owner_rows:
        oid = row["owner_id"]
        if not oid or oid in owners:
            errors.append(f"duplicate or empty owner_id: {oid!r}")
            continue
        if row["assignment_state"] not in {"assigned", "unassigned"}:
            errors.append(f"{oid}: assignment_state must be assigned/unassigned")
        if row["assignment_state"] == "assigned" and row["accountable_holder"] in {"", "-"}:
            errors.append(f"{oid}: assigned role has no accountable_holder")
        if row["assignment_state"] == "unassigned" and row["escalation"] in {"", "-"}:
            errors.append(f"{oid}: unassigned role has no escalation")
        owners[oid] = row

    register, declaration_errors = load_register(work_path, policy, owners, oi_records)
    errors.extend(declaration_errors)
    source_records = declared_routing(open_items_path, register)

    active: list[WorkRow] = []
    promoted_records: set[str] = set()
    for item, row in sorted(register.items(), key=lambda pair: natural_item_key(pair[0])):
        if row.promotion != "promoted":
            continue
        promoted_records.add(row.source_record)
        owner = owners.get(row.owner_id)
        if owner is None or row.impact not in policy["impact_weights"] \
                or row.urgency not in policy["urgency_weights"] \
                or row.queue not in policy["queue_weights"]:
            continue                            # already reported by load_register
        queue, action = row.queue, row.next_action
        if owner["assignment_state"] == "unassigned":
            queue = policy["unassigned_owner_queue"]
            action = policy["unassigned_action_prefix"] + action[0].lower() + action[1:]
            owner_display = f"{owner['display_name']} → {owner['escalation']}"
        else:
            owner_display = owner["display_name"]
        score = (policy["impact_weights"][row.impact] + policy["urgency_weights"][row.urgency]
                 + policy["queue_weights"][queue])
        active.append(WorkRow(item, queue, owner_display, action, row.evidence,
                              f"{row.impact}/{row.urgency}", score))

    seen_pb: set[str] = set()
    active_pb: list[dict[str, str]] = []
    inactive_pb: list[dict[str, str]] = []
    for row in playbook_rows:
        key = row["key"]
        if not re.fullmatch(r"PB-\d{2}", key):
            errors.append(f"invalid playbook key: {key!r}")
        if key in seen_pb:
            errors.append(f"duplicate playbook key: {key}")
        seen_pb.add(key)
        if row["state"] not in {"active", "retired"}:
            errors.append(f"{key}: state must be active/retired")
            continue
        cited = re.findall(r"BEN-\d{3}", row["evidence"])
        if not cited:
            errors.append(f"{key}: cites no BEN evidence")
        for ben in cited:
            if ben not in ben_ids:
                errors.append(f"{key}: cites missing {ben}")
        if not row["operating_rule"] or not row["observable_check"]:
            errors.append(f"{key}: rule and observable_check are required")
        if row["state"] == "active":
            active_pb.append(row)
        else:
            if row["retirement_reason"] in {"", "-"}:
                errors.append(f"{key}: retired rule needs retirement_reason")
            inactive_pb.append(row)

    active.sort(key=lambda row: (-row.score, natural_item_key(row.item)))
    active_pb.sort(key=lambda row: int(row["key"].split("-")[1]))
    minimum, cap = policy["current_work_min"], policy["current_work_cap"]
    if len(active) < minimum:
        errors.append(f"active work has {len(active)} rows; minimum is {minimum}")
    if not policy["playbook_min"] <= len(active_pb) <= policy["playbook_cap"]:
        errors.append(f"active playbook has {len(active_pb)} rows; allowed range is "
                      f"{policy['playbook_min']}-{policy['playbook_cap']}")
    selected, overflow = active[:cap], active[cap:]
    # Backlog membership is per SOURCE RECORD, while `promotion` is per ROW: a record whose work is
    # decomposed into leaves (OI-131) has an unpromoted source row and is still not backlog.
    unpromoted = [record for record in source_records
                  if record.lifecycle == "active" and record.key not in promoted_records]
    return policy, selected, overflow, active_pb, inactive_pb, source_records, unpromoted, errors


def render_current(policy: dict, selected: list[WorkRow]) -> str:
    mode = "CANONICAL" if policy.get("canonical_adoption_allowed") else "PROTOTYPE"
    lines = [
        "# Current work — bounded attention queue", "",
        f"> **{mode}; GENERATED by `docs/orchestration/control_plane_lint.py --write`. Do not hand-edit.**",
        "> Sources: `control-plane/policy.json`, `owners.tsv`, and `work-items.tsv`. Full scientific",
        "> state and evidence remain in `docs/OPEN_ITEMS.md`; this view is authoritative only for routing.", "",
        f"Policy selects the top {policy['current_work_cap']} promoted leaves by impact, urgency,",
        "and effective queue. Unassigned roles are automatically routed to `WAITING-JOSEPH`. Ties use",
        "numeric OI id and sub-item. Source lifecycle and queue are DECLARED in `work-items.tsv`,",
        "never derived from OI state prose; terminal and deferred records never enter this page.",
        "",
        "| item | queue | accountable owner | basis | next action | evidence route |",
        "|---|---|---|---|---|---|",
    ]
    for row in selected:
        lines.append(f"| {row.item} | {row.queue} | {row.owner} | {row.basis} | {row.action} | {row.evidence} |")
    lines += ["", "## Machine-enforced contract", "",
              f"- Rendered membership is capped at {policy['current_work_cap']}; overflow is generated at "
              "`docs/CURRENT_WORK_OVERFLOW.md`.",
              "- An unassigned owner cannot render as `NOW`.",
              "- Queue order and tie-breaking come only from the checked-in policy, never table position.",
              "- Lifecycle and queue are read from the declared register only. No wording in",
              "  `docs/OPEN_ITEMS.md` outside a record's id token can change either one.",
              "- A source record with no register row fails the commit; there is no permissive "
              "default."]
    return "\n".join(lines) + "\n"


def render_overflow(policy: dict, overflow: list[WorkRow]) -> str:
    lines = ["# Current-work overflow", "",
             "> GENERATED by `docs/orchestration/control_plane_lint.py --write`. Do not hand-edit.", "",
             f"Items below were eligible but fell below the top-{policy['current_work_cap']} cutoff. "
             "They are not terminal and are not silently deferred.", "",
             "| item | effective queue | owner | basis | score | evidence |",
             "|---|---|---|---|---:|---|"]
    if overflow:
        for row in overflow:
            lines.append(f"| {row.item} | {row.queue} | {row.owner} | {row.basis} | {row.score} | {row.evidence} |")
    else:
        lines.append("| — | — | — | — | — | No eligible item currently falls below the cap. |")
    return "\n".join(lines) + "\n"


def render_backlog(records: list[SourceRecord]) -> str:
    lines = ["# Unpromoted open-item backlog", "",
             "> GENERATED by `docs/orchestration/control_plane_lint.py --write`. Do not hand-edit.", "",
             "These source records classify as active but have no promoted actionable leaf. They remain",
             "visible here and in `OPEN_ITEMS.md`; omission from `CURRENT_WORK.md` is not retirement.", "",
             "| source record | derived queue | classification rule | source state prefix |",
             "|---|---|---|---|"]
    if records:
        for row in records:
            prefix = row.state_prefix.replace("|", "\\|")
            lines.append(f"| {row.key} | {row.queue} | {row.rule} | {prefix} |")
    else:
        lines.append("| — | — | — | Every active source record has a promoted leaf. |")
    return "\n".join(lines) + "\n"


def render_playbook(policy: dict, rows: list[dict[str, str]]) -> str:
    mode = "CANONICAL" if policy.get("canonical_adoption_allowed") else "PROTOTYPE"
    lines = ["# Active campaign playbook", "",
             f"> **{mode}; GENERATED by `docs/orchestration/control_plane_lint.py --write`. Do not hand-edit.**",
             "> Source: `control-plane/playbook.tsv`. `FINDINGS.md` remains the evidence casebook and is",
             "> opened on demand by BEN id.", "",
             "| key | operating rule | executable or observable check | evidence |",
             "|---|---|---|---|"]
    for row in rows:
        lines.append(f"| {row['key']} | {row['operating_rule']} | {row['observable_check']} | {row['evidence']} |")
    lines += ["", "## Promotion and retirement", "",
              "- Search the casebook first; a new BEN must change a check, rule, or established scope.",
              f"- At most {policy['playbook_cap']} rules may be active. Promoting another rule at the cap "
              "requires retiring or consolidating one in the same source change.",
              "- Retirement preserves the TSV row, BEN evidence, and a non-empty reason; it removes only",
              "  default-read status, not history."]
    return "\n".join(lines) + "\n"


def generated_outputs(**paths) -> tuple[dict[Path, str], list[str], dict, int]:
    policy, selected, overflow, playbook, _, source_records, unpromoted, errors = load_model(**paths)
    outputs = {CURRENT: render_current(policy, selected),
               OVERFLOW: render_overflow(policy, overflow),
               BACKLOG: render_backlog(unpromoted),
               SOURCE_INVENTORY: render_inventory(source_records),
               PLAYBOOK: render_playbook(policy, playbook)}
    drifted = sum(1 for record in source_records if record.state_digest_drifted)
    return outputs, errors, policy, drifted


def registry_coverage(open_items_path: Path = OPEN_ITEMS,
                      work_path: Path = WORK_ITEMS) -> tuple[int, int, int, Counter, Counter]:
    rows = [RegisterRow(**row) for row in read_tsv(work_path, REGISTER_COLUMNS)]
    records = declared_routing(open_items_path, {row.item: row for row in rows})
    promoted = {row.source_record for row in rows if row.promotion == "promoted"}
    active = {record.key for record in records if record.lifecycle == "active"}
    counts = Counter((record.lifecycle, record.queue) for record in records)
    return (len(records), len(promoted), len(active - promoted), counts,
            Counter(record.rule for record in records))


def adoption_errors(policy: dict) -> list[str]:
    errors = []
    if not policy.get("canonical_adoption_allowed"):
        errors.append("canonical adoption is disabled in policy.json")
    if policy.get("registry_scope") != "all-open-items-records":
        errors.append("registry_scope must be all-open-items-records before adoption")
    return errors


CANONICAL_CLAUDE_ROUTE = (
    "Read `AGENTS.md` before acting; it is the shared scientific front door and routes every "
    "specialized task to its governing evidence. This file is only the automatically loaded bootstrap."
)

CANONICAL_CLAUDE_BULLETS = (
    "Treat the front door and generated state as views, never evidence or authorization.",
    "Before quoting, writing, computing, or deciding a gate, open the routed canonical artifact and "
    "re-measure volatile fields.",
    "A result is live only after its evidence and required records land in a commit.",
    "Audit and review work is read-only and uses an isolated worktree; inspect status afterward.",
    "Pre-freeze provenance may leave `main` only through the pushed evidence tag, tested recovery, "
    "an exact removal-family authorization, and a surviving discovery route.",
    "Domain, environment, and scheduler rules are task-specific; follow the route in `AGENTS.md` "
    "rather than inferring them from memory.",
)

CANONICAL_INTEGRITY_RULES = (
    "This front door and generated state are views, never evidence or authorization.",
    "A result is live only after its evidence and required ledger/RUN_LOG/STATUS records land in a "
    "commit. Uncommitted or merely relayed results are not quotable.",
    "Worker agreement is not independence. Trace agreeing statements to their first measurement and "
    "count shared origins once.",
    "Generated state is a view, not truth. Run its freshness check, then observe the governing source "
    "or scheduler before acting.",
    "Audit and review work is read-only. Use isolated worktrees, inspect status afterward, and never "
    "freeze an auditor's silent edit into a receipt.",
    "Pre-freeze provenance may leave `main` only through the pushed evidence tag, tested recovery, "
    "an exact removal-family authorization, and a surviving discovery route.",
    "Domain-specific contracts live behind task routes. Do not reconstruct a pipeline from this summary.",
)


def markdown_bullets(section: str) -> tuple[list[str], bool]:
    """Return normalized bullets and whether non-bullet prose/comments were present."""
    bullets: list[str] = []
    invalid = False
    for raw in section.splitlines():
        if not raw.strip():
            continue
        if raw.startswith("- "):
            bullets.append(raw[2:].strip())
        elif raw.startswith("  ") and bullets:
            bullets[-1] += " " + raw.strip()
        else:
            invalid = True
    return bullets, invalid


def bootstrap_contract_errors(agents: str, claude: str, playbook: str) -> list[str]:
    """Validate the thin shared front door without requiring duplicated bootstrap prose."""
    errors: list[str] = []
    if len(agents.splitlines()) > 150:
        errors.append("AGENTS.md exceeds the 150-line front-door cap")
    if len(claude.splitlines()) > 20:
        errors.append("CLAUDE.md exceeds the 20-line bootstrap cap")
    for required in ("docs/CURRENT_WORK.md", "docs/orchestration/PLAYBOOK.md"):
        if required not in agents:
            errors.append(f"AGENTS.md does not route to {required}")
    claude_blocks = [block for block in re.split(r"\n\s*\n", claude)
                     if block.strip() and not block.lstrip().startswith("#")]
    claude_paragraphs = [" ".join(block.split()) for block in claude_blocks]
    if not claude_paragraphs or claude_paragraphs[0] != CANONICAL_CLAUDE_ROUTE:
        errors.append("CLAUDE.md does not begin with the exact canonical AGENTS.md route")
    claude_bullets, invalid_claude = markdown_bullets("\n\n".join(claude_blocks[1:]))
    if invalid_claude or tuple(claude_bullets) != CANONICAL_CLAUDE_BULLETS:
        errors.append("CLAUDE.md bootstrap rules do not match the canonical bullet contract")
    if claude.count("AGENTS.md") != 2:
        errors.append("CLAUDE.md must contain exactly its two canonical AGENTS.md routes")
    integrity = re.search(
        r"^## Minimal integrity rules\n(.*?)(?=^## )", agents, re.MULTILINE | re.DOTALL)
    if not integrity:
        errors.append("AGENTS.md has no bounded Minimal integrity rules section")
    integrity_text = integrity.group(1) if integrity else ""
    integrity_bullets, invalid_integrity = markdown_bullets(integrity_text)
    if invalid_integrity or tuple(integrity_bullets) != CANONICAL_INTEGRITY_RULES:
        errors.append("AGENTS.md Minimal integrity rules do not match the canonical bullet contract")
    active_bens = set(re.findall(r"BEN-\d{3}", playbook))
    duplicated_bens = sorted(active_bens & set(re.findall(
        r"BEN-\d{3}", integrity_text)))
    if duplicated_bens:
        errors.append("AGENTS.md duplicates BEN-backed playbook rules in Minimal integrity rules: "
                      + ", ".join(duplicated_bens))
    return errors


def check_or_write(write: bool, adoption: bool = False) -> int:
    outputs, errors, policy, drifted = generated_outputs()
    if adoption:
        errors.extend(adoption_errors(policy))
    for path, expected in outputs.items():
        if write:
            path.write_text(expected, encoding="utf-8")
        elif not path.exists() or path.read_text(encoding="utf-8") != expected:
            errors.append(f"generated output stale: {path.relative_to(REPO)}; run --write")
    errors.extend(bootstrap_contract_errors(
        AGENTS.read_text(encoding="utf-8"), CLAUDE.read_text(encoding="utf-8"), outputs[PLAYBOOK]))
    catalog = (REPO / "docs/orchestration/CATALOG.md").read_text(encoding="utf-8")
    for required in ("CURRENT_WORK.md", "CURRENT_WORK_OVERFLOW.md", "CURRENT_WORK_BACKLOG.md",
                     "PLAYBOOK.md", "control-plane/policy.json", "source-record-inventory.tsv"):
        if required not in catalog:
            errors.append(f"CATALOG.md does not route to {required}")
    if errors:
        for error in errors:
            print(f"CONTROL-PLANE FAIL: {error}")
        return 1
    verb = "WROTE" if write else "PASS"
    selected = len(re.findall(r"^\| OI-", outputs[CURRENT], re.MULTILINE))
    overflow = len(re.findall(r"^\| OI-", outputs[OVERFLOW], re.MULTILINE))
    backlog = len(re.findall(r"^\| OI-", outputs[BACKLOG], re.MULTILINE))
    active_pb = len(re.findall(r"^\| PB-", outputs[PLAYBOOK], re.MULTILINE))
    inventory = len(outputs[SOURCE_INVENTORY].splitlines()) - 1
    print(f"CONTROL-PLANE {verb}: {selected} selected; {overflow} overflow; {backlog} backlog; "
          f"{inventory} source records; {active_pb} playbook rules; "
          f"{drifted} state cells changed since declaration; "
          f"{orchestration_volume()}")
    return 0


def self_test() -> int:
    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        policy = json.loads(POLICY.read_text())
        policy.update({"current_work_min": 1, "current_work_cap": 2,
                       "playbook_min": 1, "playbook_cap": 2})
        (root / "policy.json").write_text(json.dumps(policy))
        (root / "owners.tsv").write_text(
            "\t".join(OWNER_COLUMNS) + "\n"
            "held\tHeld\tLane H\tJoseph\tassigned\n"
            "vacant\tVacant\t-\tJoseph\tunassigned\n")
        (root / "OPEN_ITEMS.md").write_text(
            "| OI-1 | OPEN | x | x | x |\n| OI-2 | OPEN | x | x | x |\n| OI-3 | OPEN | x | x | x |\n")
        (root / "FINDINGS.md").write_text("| BEN-001 | x | x | x |\n| BEN-002 | x | x | x |\n")
        base_register = {
            "OI-1": dict(owner_id="held", impact="maintenance", urgency="P3",
                         next_action="act one"),
            "OI-2": dict(owner_id="vacant", impact="publication", urgency="P0",
                         next_action="act two"),
            "OI-3": dict(owner_id="held", impact="safety", urgency="P1", next_action="act three"),
        }

        def register_row(item: str, **overrides: str) -> str:
            record = overrides.pop("source_record", item)
            fields = dict(item=item, source_record=record, lifecycle="active", queue="NOW",
                          promotion="promoted", artifact=MIGRATION_SENTINEL,
                          authority=MIGRATION_SENTINEL,
                          terminal_criterion=MIGRATION_SENTINEL,
                          evidence=f"docs/OPEN_ITEMS.md {record}", state_digest="-")
            fields.update(base_register.get(item, dict(owner_id="held", impact="safety",
                                                       urgency="P1", next_action="act n")))
            fields.update(overrides)
            return "\t".join(fields[column] for column in REGISTER_COLUMNS) + "\n"

        def register_text(patch: dict[str, dict[str, str]] | None = None,
                          drop: tuple[str, ...] = (), extra: str = "") -> str:
            rows = "".join(register_row(item, **(patch or {}).get(item, {}))
                           for item in base_register if item not in drop)
            return "\t".join(REGISTER_COLUMNS) + "\n" + rows + extra

        def registered(policy_path: Path | None = None, open_items: Path | None = None,
                       **kwargs):
            """Load the model from a mutated register. Every arm keeps all three records declared
            unless it is the coverage arm, so an unrelated fail-closed error cannot masquerade as a
            pass of the rule under test."""
            mutated = root / "work-mutated.tsv"
            mutated.write_text(register_text(**kwargs))
            return load_model(policy_path or (root / "policy.json"), root / "owners.tsv", mutated,
                              root / "play.tsv", open_items or (root / "OPEN_ITEMS.md"),
                              (root / "FINDINGS.md",))

        def register_errors(policy_path: Path | None = None, **kwargs) -> list[str]:
            return registered(policy_path, **kwargs)[-1]

        RETIRED_ROW = {"lifecycle": "retired", "queue": "-", "promotion": "-", "impact": "-",
                       "urgency": "-", "artifact": "-", "next_action": "-",
                       "terminal_criterion": "-"}

        (root / "work.tsv").write_text(register_text())
        closed_policy = dict(policy)
        closed_policy["routing"] = dict(policy["routing"], migration_open=False)
        (root / "policy-closed.json").write_text(json.dumps(closed_policy))
        (root / "play.tsv").write_text(
            "\t".join(PLAYBOOK_COLUMNS) + "\n"
            "PB-01\tactive\trule\tcheck\tBEN-001\t-\n"
            "PB-02\tretired\told rule\told check\tBEN-002\tconsolidated into PB-01\n")
        loaded = load_model(root / "policy.json", root / "owners.tsv", root / "work.tsv",
                            root / "play.tsv", root / "OPEN_ITEMS.md", (root / "FINDINGS.md",))
        _, selected, overflow, active_pb, inactive_pb, source_records, unpromoted, errors = loaded
        duplicate_fixture = root / "OPEN_ITEMS-duplicates.md"
        duplicate_fixture.write_text(
            "| OI-1 | OPEN | x | x | x |\n| OI-1 | CLOSED | x | x | x |\n"
            "| OI-2 | OPEN | x | x | x |\n")
        # ---- Prose is inert. The fixture cell is the REAL OI-126 state cell, taken from the
        # ---- producer rather than written to match a rule: 3,715 characters whose head says the
        # ---- row needs no ruling and which still contains "NEEDS JOSEPH'S RULING" further in.
        # ---- Each mutation below flipped the rendered queue under the deleted engine.
        real_row = next(line for line in OPEN_ITEMS.read_text(encoding="utf-8").splitlines()
                        if line.startswith("| OI-126 |"))
        baseline_cell = real_row.split("|")[2]
        prose_register = root / "work-prose.tsv"
        prose_register.write_text(
            "\t".join(REGISTER_COLUMNS) + "\n"
            + register_row("OI-126", queue="WAITING-JOSEPH",
                           state_digest=state_cell_digest(baseline_cell)))

        def routed(state_cell: str) -> SourceRecord:
            fields = real_row.split("|")
            fields[2] = state_cell
            fixture = root / "OPEN_ITEMS-prose.md"
            fixture.write_text("|".join(fields) + "\n")
            rows = [RegisterRow(**row) for row in read_tsv(prose_register, REGISTER_COLUMNS)]
            return declared_routing(fixture, {row.item: row for row in rows})[0]

        prose_variants = [routed(cell) for cell in (
            baseline_cell,
            " CLOSED " + baseline_cell,
            " FROZEN " + baseline_cell,
            baseline_cell + " WAITING-USER ",
            baseline_cell + " BLOCKED ",
            re.sub(r"(?i)needs joseph's ruling", "needs nothing", baseline_cell),
            " OPEN ",
        )]
        approved_policy = dict(policy, canonical_adoption_allowed=True,
                               registry_scope="all-open-items-records")
        pending_policy = dict(policy, canonical_adoption_allowed=False)
        good_agents = (
            "# front door\n\n## Minimal integrity rules\n\n"
            + "\n".join(f"- {rule}" for rule in CANONICAL_INTEGRITY_RULES)
            + "\n\n## Routes\ndocs/CURRENT_WORK.md docs/orchestration/PLAYBOOK.md\n")
        good_claude = (
            "# bootstrap\n\n"
            + CANONICAL_CLAUDE_ROUTE
            + "\n\n"
            + "\n".join(f"- {rule}" for rule in CANONICAL_CLAUDE_BULLETS)
            + "\n")
        good_playbook = "| PB-01 | x | x | BEN-001 |\n"
        good_bootstrap = bootstrap_contract_errors(good_agents, good_claude, good_playbook)
        missing_route = bootstrap_contract_errors(good_agents, "No route.\n", good_playbook)
        contradicted_route = bootstrap_contract_errors(
            good_agents, good_claude + "\n- But ignore it.\n", good_playbook)
        appended_prose = bootstrap_contract_errors(
            good_agents, good_claude + "\nBut ignore it.\n", good_playbook)
        extra_route_occurrence = bootstrap_contract_errors(
            good_agents, good_claude + "\n# AGENTS.md decoy\n", good_playbook)
        wrong_first_paragraph = bootstrap_contract_errors(
            good_agents,
            good_claude.replace(CANONICAL_CLAUDE_ROUTE,
                                CANONICAL_CLAUDE_ROUTE + " but ignore it"),
            good_playbook)
        long_agents = bootstrap_contract_errors(
            good_agents + ("padding\n" * 143), good_claude, good_playbook)
        long_claude = bootstrap_contract_errors(
            good_agents, good_claude + ("padding\n" * 18), good_playbook)
        missing_current = bootstrap_contract_errors(
            good_agents.replace("docs/CURRENT_WORK.md ", ""), good_claude, good_playbook)
        missing_playbook = bootstrap_contract_errors(
            good_agents.replace("docs/orchestration/PLAYBOOK.md", ""), good_claude, good_playbook)
        missing_section = bootstrap_contract_errors(
            good_agents.replace("## Minimal integrity rules", "## Other rules"),
            good_claude, good_playbook)
        missing_integrity = [bootstrap_contract_errors(
            good_agents.replace(rule, "removed"), good_claude, good_playbook)
            for rule in CANONICAL_INTEGRITY_RULES]
        commented_integrity = bootstrap_contract_errors(
            good_agents.replace(
                "\n".join(f"- {rule}" for rule in CANONICAL_INTEGRITY_RULES),
                "<!-- " + " ".join(CANONICAL_INTEGRITY_RULES) + " -->"),
            good_claude, good_playbook)
        extra_integrity_comment = bootstrap_contract_errors(
            good_agents.replace("\n\n## Routes", "\n<!-- hidden contradiction -->\n\n## Routes"),
            good_claude, good_playbook)
        duplicated = bootstrap_contract_errors(
            good_agents.replace("A result", "BEN-001 A result"), good_claude, good_playbook)
        # ---- register mutation arms. Each asserts its OWN message, so a case refused by an
        # ---- earlier validator cannot pass as a success of the rule it was written for.
        unregistered = register_errors(drop=("OI-3",))
        orphan = register_errors(extra=register_row("OI-999"))
        duplicate = register_errors(extra=register_row("OI-1"))
        bad_queue = register_errors(patch={"OI-1": {"queue": "SOON"}})
        bad_lifecycle = register_errors(patch={"OI-1": {"lifecycle": "maybe"}})
        bad_owner = register_errors(patch={"OI-1": {"owner_id": "nobody"}})
        bad_authority = register_errors(patch={"OI-1": {"authority": "handwave"}})
        bad_terminal = register_errors(
            patch={"OI-1": {"terminal_criterion": "someday it will be fine"}})
        typed_terminal = register_errors(
            patch={"OI-1": {"terminal_criterion": "commit: the row lands"}})
        retired_with_queue = register_errors(patch={"OI-1": {"lifecycle": "retired"}})
        active_without_queue = register_errors(patch={"OI-1": {"queue": "-"}})
        unpriced_queue = register_errors(patch={"OI-1": {"queue": "BLOCKED-INTERNAL"}})
        promoted_without_action = register_errors(patch={"OI-1": {"next_action": "-"}})
        backlog_with_score = register_errors(
            patch={"OI-1": {"promotion": "backlog", "next_action": "-", "urgency": "-",
                            "artifact": "-"}})
        backlog_clean = register_errors(
            patch={"OI-1": {"promotion": "backlog", "next_action": "-", "urgency": "-",
                            "impact": "-", "artifact": "-"}})
        leaf_with_lifecycle = register_errors(
            extra=register_row("OI-1(a)", source_record="OI-1", lifecycle="active"))
        leaf_pair = register_errors(
            patch={"OI-1": {"promotion": "backlog", "next_action": "-", "urgency": "-",
                            "impact": "-", "artifact": "-"}},
            extra=(register_row("OI-1(a)", source_record="OI-1", lifecycle="-",
                                queue="WAITING-JOSEPH")
                   + register_row("OI-1(b)", source_record="OI-1", lifecycle="-",
                                  queue="BLOCKED-EXTERNAL")))
        wrong_parent = register_errors(
            extra=register_row("OI-1(a)", source_record="OI-2", lifecycle="-"))
        # The prefix regression: 'OI-10'.startswith('OI-1') is True, so a substring test would
        # have accepted this row as a declaration for OI-1.
        prefix_collision = register_errors(extra=register_row("OI-10", source_record="OI-1"))
        migration_closed = register_errors(policy_path=root / "policy-closed.json")
        migration_closed_declared = register_errors(
            policy_path=root / "policy-closed.json",
            patch={item: {"authority": "self-filed:2026-09-02",
                          "terminal_criterion": "commit: it lands",
                          "artifact": "AGENTS.md"} for item in base_register})
        artifact_path = register_errors(patch={"OI-1": {"artifact": "AGENTS.md"}})
        artifact_missing = register_errors(patch={"OI-1": {"artifact": "no/such/path.md"}})
        artifact_digest = register_errors(
            patch={"OI-1": {"artifact": "sha256:" + "a" * 64}})
        authority_tracked = register_errors(
            patch={"OI-1": {"authority": "AGENTS.md#anchor"}})
        authority_untracked = register_errors(
            patch={"OI-1": {"authority": "no/such/file.md#anchor"}})
        # Prose that contradicts a declaration is not a defect; it is the design working. Both
        # arms below were transcription ERRORS in the migration stage and are clean now.
        contradicting_prose = root / "OPEN_ITEMS-contradiction.md"
        contradicting_prose.write_text(
            "| OI-1 | CLOSED | x |\n| OI-2 | OPEN | x |\n| OI-3 | OPEN | x |\n")
        prose_says_closed = registered(open_items=contradicting_prose)
        prose_says_open = registered(patch={"OI-1": dict(RETIRED_ROW)})

        # The declaration is live: move one queue cell and the render and the score both move.
        declared_now = registered()
        declared_waiting = registered(patch={"OI-3": {"queue": "WAITING-JOSEPH"}})
        queue_delta = (policy["queue_weights"]["WAITING-JOSEPH"] - policy["queue_weights"]["NOW"])
        moved = {row.item: row for row in declared_waiting[1] + declared_waiting[2]}
        held = {row.item: row for row in declared_now[1] + declared_now[2]}

        # state_digest is report-only: it must never route and never fail a commit.
        drifted_run = registered(patch={"OI-1": {"state_digest": "sha256:" + "b" * 64}})
        drifted_records = {record.key: record for record in drifted_run[5]}

        # The classifier was DELETED, not bypassed.
        live_policy = json.loads(POLICY.read_text(encoding="utf-8"))

        checks = [not errors, [row.item for row in selected] == ["OI-2", "OI-3"],
                  selected[0].queue == "WAITING-JOSEPH", len(overflow) == 1,
                  len(active_pb) == 1, len(inactive_pb) == 1,
                  len(source_records) == 3, not unpromoted,
                  source_oi_records(duplicate_fixture) == ["OI-1#1", "OI-1#2", "OI-2"],
                  {(record.lifecycle, record.queue) for record in prose_variants}
                  == {("active", "WAITING-JOSEPH")},
                  len({record.row_sha256 for record in prose_variants}) == len(prose_variants),
                  prose_variants[0].state_digest_drifted is False,
                  all(record.state_digest_drifted for record in prose_variants[1:]),
                  bool(adoption_errors(pending_policy)), not adoption_errors(approved_policy),
                  not good_bootstrap,
                  any("canonical AGENTS.md route" in error for error in missing_route),
                  any("canonical bullet contract" in error for error in contradicted_route),
                  any("canonical bullet contract" in error for error in appended_prose),
                  any("exactly its two" in error for error in extra_route_occurrence),
                  any("exact canonical AGENTS.md route" in error
                      for error in wrong_first_paragraph),
                  any("150-line" in error for error in long_agents),
                  any("20-line" in error for error in long_claude),
                  any("CURRENT_WORK.md" in error for error in missing_current),
                  any("PLAYBOOK.md" in error for error in missing_playbook),
                  any("no bounded" in error for error in missing_section),
                  all(any("canonical bullet contract" in error for error in result)
                      for result in missing_integrity),
                  any("canonical bullet contract" in error for error in commented_integrity),
                  any("canonical bullet contract" in error for error in extra_integrity_comment),
                  any("duplicates BEN-backed" in error for error in duplicated),
                  any("has no routing declaration" in error for error in unregistered),
                  any("absent from OPEN_ITEMS.md" in error for error in orphan),
                  any("duplicate register row for item OI-1" in error for error in duplicate),
                  any("invalid queue 'SOON'" in error for error in bad_queue),
                  any("invalid lifecycle 'maybe'" in error for error in bad_lifecycle),
                  any("unknown owner_id 'nobody'" in error for error in bad_owner),
                  any("invalid authority 'handwave'" in error for error in bad_authority),
                  any("terminal_criterion must read" in error for error in bad_terminal),
                  not typed_terminal,
                  any("non-active row must use '-' for queue" in error
                      for error in retired_with_queue),
                  any("invalid queue '-'" in error for error in active_without_queue),
                  any("has no weight in queue_weights" in error for error in unpriced_queue),
                  any("next_action must be 1-260" in error for error in promoted_without_action),
                  any("unpromoted row must use '-' for impact" in error
                      for error in backlog_with_score),
                  not backlog_clean,
                  any("leaf row must inherit lifecycle" in error for error in leaf_with_lifecycle),
                  not leaf_pair,
                  any("different parent id" in error for error in wrong_parent),
                  any("different parent id" in error for error in prefix_collision),
                  all(any(f"{column} is 'migration-carried-forward' but the migration is closed"
                          in error for error in migration_closed)
                      for column in MIGRATABLE_COLUMNS),
                  not migration_closed_declared,
                  not artifact_path, not artifact_digest,
                  any("is not a repo path" in error for error in artifact_missing),
                  not authority_tracked,
                  any("is not tracked" in error for error in authority_untracked),
                  not prose_says_closed[-1],
                  [row.item for row in prose_says_closed[1]] == ["OI-2", "OI-3"],
                  not prose_says_open[-1],
                  [row.item for row in prose_says_open[1] + prose_says_open[2]] == ["OI-2", "OI-3"],
                  moved["OI-3"].queue == "WAITING-JOSEPH" and held["OI-3"].queue == "NOW",
                  moved["OI-3"].score - held["OI-3"].score == queue_delta,
                  not drifted_run[-1],
                  drifted_records["OI-1"].state_digest_drifted,
                  drifted_records["OI-1"].queue == "NOW",
                  "normalize_state" not in globals(),
                  "classify_source_records" not in globals(),
                  "source_classification" not in live_policy,
                  "ordered_rules" not in live_policy.get("routing", {})]
        if not all(checks):
            print("control-plane self-test: FAIL")
            # The suite is a flat list of assertions, so report WHICH ones failed: a bare
            # pass/fail over 60 arms cannot tell you which rule regressed.
            print("failing check indices:", [i for i, ok in enumerate(checks) if not ok])
            print("errors:", errors)
            print("selected:", selected, "overflow:", overflow)
            return 1
    print("control-plane self-test: PASS")
    return 0


def coverage_report() -> int:
    total, promoted, backlog, counts, rules = registry_coverage()
    print(f"CONTROL-PLANE COVERAGE: {total}/{total} source records declared")
    print(f"promoted source records: {promoted}; active unpromoted backlog: {backlog}")
    for (lifecycle, queue), count in sorted(counts.items()):
        print(f"{lifecycle:8} {queue:16} {count}")
    print("routing authority:")
    for rule, count in sorted(rules.items()):
        print(f"{rule:28} {count}")
    drifted = sum(1 for record in declared_routing(
        OPEN_ITEMS, {row.item: row for row in
                     [RegisterRow(**r) for r in read_tsv(WORK_ITEMS, REGISTER_COLUMNS)]})
        if record.state_digest_drifted)
    print(f"state cells changed since declaration: {drifted} (report-only; routes nothing)")
    return 0


def orchestration_volume() -> str:
    """Prose lines and instrument lines under docs/orchestration, reported SEPARATELY.

    Never sum them. One number over the total makes deleting an instrument the cheapest way
    to pass a size target, and the instruments are what catch defects the prose does not.
    Reported here rather than in a document so the measurement costs no reading.

    Counts TRACKED files only. The first version walked the working tree with rglob and so
    counted other lanes' untracked strays: measured 42785 vs 42777 tracked with one lane's
    scratch present, meaning two lanes at the SAME commit printed different numbers and a
    quoted trend could show the layer growing when nothing had been written.

    THIS COSTS ABOUT 2x AND IS WORTH IT. Measured like-for-like, both arms doing the full
    line count, best of 5: the rglob walk 17.2 ms, this 33.5 ms. Roughly 16 ms per commit to
    make a published number reproducible across lanes is an obvious buy, but it is NOT free
    and nobody should reason from a claim that it was. The commit that introduced this
    function (d3cdc6d3) says "cheaper as well as reproducible" and that is FALSE: it
    compared `git ls-files` ALONE (18.3 ms) against the rglob path INCLUDING every
    `read_text` (28 ms). The reads are common to both arms and belong on both sides or
    neither; the honest enumeration-only pair is 18.3 ms of git against 2.1 ms of walk.
    Separately and still true: the 0.87 s that first ruled a git subprocess out of this
    function was `git log --since --name-only` walking HISTORY, which is a different command
    from an index read and did not generalize.

    Boundary, stated so this is not mistaken for a tree-of-record figure: it counts
    tracked PATHS with WORKING-TREE content. A lane's uncommitted edit to a tracked file
    still moves it; an untracked file no longer does.

    Non-raising: this is pre-commit check 10 for every lane. On any git failure it reports
    unavailable rather than falling back to a working-tree walk, because silently changing
    the measurement basis under the same label is worse than a missing number.
    """
    try:
        proc = subprocess.run(
            ["git", "-C", str(REPO), "ls-files", "-z", "--", "docs/orchestration"],
            capture_output=True, timeout=15, check=False)
        if proc.returncode != 0:
            return f"prose/instrument volume unavailable (ls-files rc={proc.returncode})"
        names = [n for n in proc.stdout.decode("utf-8", "replace").split("\0") if n]
        if not names:
            # PB-15: zero must be distinguishable from unmeasured. `git ls-files` exits 0 for
            # a path it knows nothing about, so an empty match set would otherwise print
            # "0 prose / 0 instrument" -- a measurement never made, and indistinguishable
            # from a genuinely empty layer. Fires on a rename of the path with no code change.
            return "prose/instrument volume unavailable (no tracked paths under docs/orchestration)"

        def lines(suffix: str) -> int:
            total = 0
            for name in names:
                if not name.endswith(suffix):
                    continue
                try:
                    total += len((REPO / name).read_text(
                        encoding="utf-8", errors="replace").splitlines())
                except OSError:
                    continue    # tracked but absent from the worktree: skip, never fail
            return total

        return (f"{lines('.md')} prose / {lines('.py')} instrument lines"
                f" over {len(names)} tracked files")
    except (OSError, subprocess.SubprocessError):
        return "prose/instrument volume unavailable"


def _label(path: Path) -> str:
    try:
        return str(path.relative_to(REPO))
    except ValueError:      # an entrypoint outside REPO must still be reportable
        return str(path)


def _words(path: Path) -> int:
    return len(re.findall(r"\S+", path.read_text(encoding="utf-8", errors="replace")))


def entrypoint_report() -> int:
    """Two populations, never one number.

    The PRESCRIBED PATH is what every session reads before it may act. The SEARCHED CORPUS is
    what a routed file contains, of which the route asks for one record. An earlier version of
    this function summed both and labelled the result "TOTAL prescribed default path": it
    reported 69009 where the route prescribes 12848, a 5.4x overstatement, because it counted
    the container and reported about the contents. Keeping the two apart is PB-15's rule --
    print the populations, and never a figure the instrument did not measure.
    """
    prescribed = 0
    print("PRESCRIBED PATH -- read in full by every session")
    for path in FULL_READ:
        if not path.exists():
            print(f"{'absent':>7}  {_label(path)}")
            continue
        words = _words(path)
        prescribed += words
        print(f"{words:7d}  {_label(path)}")
    print(f"{prescribed:7d}  subtotal")

    corpus = 0
    print("\nPLUS the exact cited record -- NOT the whole file (AGENTS.md, Evidence routes)")
    for path in ROW_ROUTED:
        if not path.exists():
            print(f"{'absent':>7}  {_label(path)}")
            continue
        full = _words(path)
        corpus += full
        rows = sorted(len(re.findall(r"\S+", line))
                      for line in path.read_text(encoding="utf-8", errors="replace").splitlines()
                      if re.match(r"^\| *OI-", line))
        if rows:
            med = rows[len(rows) // 2]
            print(f"{med:7d}  {_label(path)}  median record of {len(rows)} "
                  f"(min {rows[0]}, max {rows[-1]})")
            print(f"{prescribed + med:7d}  PRESCRIBED PATH TOTAL, median record")
            print(f"{prescribed + rows[-1]:7d}  PRESCRIBED PATH TOTAL, largest record")
        else:
            print(f"{'n/a':>7}  {_label(path)}  no OI records matched -- cannot price a record")

    print("\nSEARCHED CORPUS -- present in routed files, not prescribed reading")
    for path in ROW_ROUTED:
        if path.exists():
            print(f"{_words(path):7d}  {_label(path)} in full")
    print(f"{prescribed + corpus:7d}  routed corpus total")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--write", action="store_true")
    group.add_argument("--coverage-report", action="store_true")
    group.add_argument("--entrypoint-report", action="store_true")
    group.add_argument("--self-test", action="store_true")
    group.add_argument("--adoption-check", action="store_true")
    args = parser.parse_args()
    if args.self_test:
        return self_test()
    if args.coverage_report:
        return coverage_report()
    if args.entrypoint_report:
        return entrypoint_report()
    return check_or_write(args.write, args.adoption_check)


if __name__ == "__main__":
    sys.exit(main())
