#!/usr/bin/env python3
"""Generate the concise orchestration dashboard from live and machine sources."""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import pathlib
import subprocess
import sys
import tempfile
from typing import Any

from slurm_array_status import build_snapshot, expand_spec


HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parents[1]
DEFAULT_CONFIG = HERE / "state" / "live-state.json"
DEFAULT_OUTPUT = HERE / "LIVE-STATE.md"
MAX_LINES = 120


def utc_now() -> str:
    return dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def load_json(path: pathlib.Path) -> dict[str, Any]:
    return json.loads(path.read_text())


def run_text(command: list[str], *, check: bool = True) -> str:
    result = subprocess.run(command, cwd=REPO, text=True, capture_output=True)
    if check and result.returncode != 0:
        raise RuntimeError(f"command failed ({result.returncode}): {' '.join(command)}: {result.stderr.strip()}")
    return result.stdout


def usage_snapshot() -> tuple[dict[str, Any], int]:
    result = subprocess.run(
        [sys.executable, str(HERE / "usagectl.py"), "snapshot", "--json"],
        cwd=REPO,
        text=True,
        capture_output=True,
    )
    try:
        return json.loads(result.stdout), result.returncode
    except json.JSONDecodeError:
        return {"gate_ok": False, "warnings": [f"usage snapshot unavailable (rc={result.returncode})"]}, result.returncode


def validate_owners(config: dict[str, Any], sessions: dict[str, Any]) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    seen: set[str] = set()
    registry = sessions.get("sessions", {})
    for owner in config["owners"]:
        role = owner["role"]
        if role not in registry:
            raise RuntimeError(f"configured owner role missing from registry: {role}")
        record = registry[role]
        actual = record.get("session_id")
        if actual != owner["uuid"]:
            raise RuntimeError(f"UUID mismatch for {role}: config={owner['uuid']} registry={actual}")
        if actual in seen:
            raise RuntimeError(f"duplicate configured owner UUID: {actual}")
        seen.add(actual)
        rows.append(
            {
                "role": role,
                "provider": f"{record.get('provider','?')}/{record.get('profile','?')}",
                "uuid": actual,
                "purpose": owner["purpose"],
            }
        )
    return rows


def rel_link(repo_path: str) -> str:
    if repo_path == "superseded followup prompts":
        return repo_path
    target = pathlib.Path(repo_path)
    return os.path.relpath(REPO / target, HERE)


def codex_capacity(usage: dict[str, Any], profile: str) -> str:
    record = usage.get("profiles", {}).get(profile, {})
    window = record.get("windows", {}).get("seven_day", {})
    remaining = window.get("remaining_percent", "unknown")
    reset = window.get("resets_at_utc", "unknown")
    credits = record.get("reset_credits", {})
    available = credits.get("valid_available_full_reset_count", "unknown")
    protected = credits.get("protected_reserve", "unknown")
    return f"{remaining}% weekly remaining; reset {reset}; Full resets {available} available/{protected} protected"


def render(
    config: dict[str, Any],
    sessions: dict[str, Any],
    usage: dict[str, Any],
    usage_rc: int,
    jobs: list[dict[str, Any]],
    git_state: dict[str, Any],
    wake_state: dict[str, Any],
    observed_at: str,
) -> str:
    owners = validate_owners(config, sessions)
    lines = [
        "# Live orchestration state",
        "",
        "> GENERATED by `generate_live_state.py`; do not hand-edit. This is the normal-turn control-plane entrypoint.",
        "",
        f"- Observed: `{observed_at}`",
        f"- Campaign: {config['campaign']}",
        f"- Current DAG node: **{config['current_dag_node']}**",
        f"- Declared state: **{config['state']}**",
        f"- Git: `{git_state['head']}`; worktree entries: {git_state['dirty_count']} (uncommitted science is never live evidence)",
        "",
        "## Owners",
        "",
        "| Role | Provider/profile | UUID | Responsibility |",
        "|---|---|---|---|",
    ]
    for owner in owners:
        lines.append(f"| `{owner['role']}` | {owner['provider']} | `{owner['uuid']}` | {owner['purpose']} |")
    lines.extend(["", "## Compute", "", "| Job | State counts | Errors | Resources / placement |", "|---|---|---|---|"])
    for job in jobs:
        receipt = job["receipt"]
        counts = ", ".join(f"{key}={value}" for key, value in job["snapshot"].get("counts", {}).items()) or "unknown"
        errors = ",".join(str(x) for x in job["snapshot"].get("error_tasks", [])) or "none"
        resources = f"{receipt.get('cpus_per_task','?')} CPU, {receipt.get('memory_per_task','?')}, {receipt.get('time_limit','?')}; {receipt.get('qos','?')} batch array"
        lines.append(f"| `{job['job_id']}_[{job['tasks']}]` | **{job['snapshot'].get('overall','UNKNOWN')}**: {counts} | {errors} | {resources} |")
    lines.extend(
        [
            "",
            "## Wake",
            "",
            f"- tmux `{config['wake']['tmux_session']}`: **{wake_state['tmux']}**",
            f"- Event/invoked/done markers: {wake_state['event']} / {wake_state['invoked']} / {wake_state['completed']}",
            f"- Resume target: `{config['orchestrator_thread_id']}` with goals disabled and full-access flag.",
            "- Only terminal COMPLETE, task ERROR, or sustained observer failure may wake the thread; ACTIVE never does.",
            "",
            "## Provider capacity",
            "",
            f"- Usage gate: **{'PASS' if usage.get('gate_ok') else 'BLOCKED/UNKNOWN'}** (helper rc={usage_rc})",
            f"- Codex personal: {codex_capacity(usage, 'codex-personal')}",
            f"- Codex school: {codex_capacity(usage, 'codex-school')}",
        ]
    )
    school = usage.get("accounts", {}).get("claude-school", {})
    agy = usage.get("profiles", {}).get("agy", {})
    lines.append(f"- Claude school shared account: {school.get('status','unknown')} (school + legacy are one quota; never sum aliases)")
    lines.append(f"- agy/Gemini: {agy.get('status','unknown')} (no percentage API; heartbeat/cap evidence only)")
    warnings = usage.get("warnings", [])
    if warnings:
        lines.append(f"- Capacity warnings: {len(warnings)}; inspect the complete snapshot before dispatch.")
    lines.extend(["", "## Exact blockers", ""])
    lines.extend(f"- {value}" for value in config["blockers"])
    lines.extend(["", "## Next authorized action", "", config["next_authorized_action"], "", "## Source routing", "", "| Class | Sources |", "|---|---|"])
    for label, key in (
        ("Canonical science", "canonical_science"),
        ("Append-only history", "append_only_history"),
        ("Archival/index-only", "archival_index_only"),
    ):
        rendered = ", ".join(f"[{path}]({rel_link(path)})" if path != "superseded followup prompts" else path for path in config[key])
        lines.append(f"| {label} | {rendered} |")
    lines.extend(
        [
            "",
            "## Fail-closed invariants",
            "",
            "- Preserve configured worker UUIDs; use `agentctl.py send`, never replacement conversations.",
            "- A scientific result is live only after its exact receipt/summary/ledger/status commit is pushed.",
            "- Do not double-count Claude School aliases or infer stale Claude/agy percentages.",
            "- Never consume the protected Codex Full reset without new credit-specific authorization.",
            "- Never use LLM polling/sleep loops; external terminal events perform at most one resume.",
            "- Choose live interactive capacity only for ready single-node work; queue independent arrays/long work early.",
            "",
        ]
    )
    if len(lines) > MAX_LINES:
        raise RuntimeError(f"dashboard exceeds {MAX_LINES} lines: {len(lines)}")
    return "\n".join(lines)


def atomic_write(path: pathlib.Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", type=pathlib.Path, default=DEFAULT_CONFIG)
    parser.add_argument("--output", type=pathlib.Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--stdout", action="store_true")
    args = parser.parse_args()

    config = load_json(args.config)
    sessions = load_json(HERE / "state" / "sessions.json")
    usage, usage_rc = usage_snapshot()
    jobs = []
    for job in config["jobs"]:
        receipt = load_json(REPO / job["receipt"])
        if receipt.get("job_id") != job["job_id"]:
            raise RuntimeError(f"job receipt mismatch for {job['job_id']}")
        jobs.append(
            {
                **job,
                "receipt": receipt,
                "snapshot": build_snapshot(job["job_id"], expand_spec(job["tasks"])),
            }
        )
    wake = config["wake"]
    tmux_rc = subprocess.run(["tmux", "has-session", "-t", wake["tmux_session"]], capture_output=True).returncode
    wake_state = {
        "tmux": "ACTIVE" if tmux_rc == 0 else "INACTIVE",
        "event": "present" if (REPO / wake["event"]).exists() else "absent",
        "invoked": "present" if (REPO / wake["invoked"]).exists() else "absent",
        "completed": "present" if (REPO / wake["completed"]).exists() else "absent",
    }
    git_state = {
        "head": run_text(["git", "rev-parse", "--short", "HEAD"]).strip(),
        "dirty_count": len(run_text(["git", "status", "--short"]).splitlines()),
    }
    output = render(config, sessions, usage, usage_rc, jobs, git_state, wake_state, utc_now())
    if args.stdout:
        print(output)
    else:
        atomic_write(args.output, output)
        print(f"wrote {args.output} ({len(output.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
