# s5p transition r3 (budget revision 7: production 234.647, owner decision 2026-10-04), resumed at the wait line observed at 04:42Z; generated by nd-unfolding/s5p_requeue.py from queues-r2
until out=$(squeue -h --me -n s5p-s5p_pow_p3g_a1p0 2>/dev/null) && [ -z "$out" ]; do sleep 120; done; echo "s5p-s5p_pow_p3g_a1p0 left the scheduler"
